### ISSUE TITLE
Upgrade to use latest openseadragon

### ISSUE THREAD

**Issue by sharmaashish** [camicroscope/caMicroscope#10]
Following up on: 
https://github.com/SBU-BMI/quip_distro/issues/40#issuecomment-280700494

**Comment by bridge2014** [comment]
alt _ mousedown function works!!!

but I find this error from browser console :+1: 
Ganesh:

Uncaught TypeError: Cannot read property 'BRIGHTNESS' of undefined    
at osdCamicroscope.php?tissueId=test_1:152

any clue?

**Comment by birm** [comment]
we're using 2.3.1 now, so I think we can close this.
