### ISSUE TITLE
QUIP 2 Issue - Delete Markup Button

### ISSUE THREAD

**Issue by tdiprima** [camicroscope/caMicroscope#100]
Someone tried to delete a markup, and the normal shortcut wouldn't work.  On QUIP1, the shortcut is (CTRL + Left Click ) on the annotation, but on QUIP2, that doesn't work.

**Comment by birm** [comment]
Not my issue, but an observation - the method starting at https://github.com/camicroscope/caMicroscope/blob/e7c690e140efdd1730352827ea3139508bae5c4e/js/annotationtools/geoJSONHandler.js#L536 references api/Data/getProperties.php which does not seem to exist.

**Comment by tdiprima** [comment]
Adding getProperties to the list #97
