### ISSUE TITLE
Table Duplication Issue on Screens Below 800px 

### ISSUE THREAD

**Issue by Joice-crypto** [camicroscope/caMicroscope#1009]
**Describe the bug**
When the screen is full, the table appears normally. However, when the screen is below 800px, the table is duplicated. This is because the components *stacktable.small-only* and *stacktable.large-only* are activated simultaneously when the screen is below 800px.

**To Reproduce**
1. Go to slides'
2. Upload something'
3. Inspect the page'
4. Change the size of the page
5. See error

**Expected behavior**
When the page has a size bellow the 800px only the stacktable.small-only has to be active. 

**Screenshots**
![A2](https://github.com/camicroscope/caMicroscope/assets/66541373/c882584d-d238-43fd-a480-813a3256fa14)

**Comment by nwanduka** [comment]
Thanks for reporting this @Joice-crypto. I've noticed it too.
