### ISSUE TITLE
Not all annotations saved have (accurate) info saved

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#1013]
Noted:

Multi mode on the pencil tool seems to save all annots as if they're the zoom/position where you save.

The preset label tool doesn't seem to save the fields at all, thus doesn't show up in the visualization in #1011 .

**Comment by YukaUU** [comment]
I solve it https://github.com/camicroscope/caMicroscope/pull/1011#issuecomment-2236869813
Please check it !

**Comment by YukaUU** [comment]
@birm 
Do I need to create a new PR for Not all annotations saved have (accurate) info saved #1013 ?

**Comment by YukaUU** [comment]
@birm 
Please cehck it https://github.com/camicroscope/caMicroscope/pull/1015
