### ISSUE TITLE
[Accessibility] Slides Page: Report link has low color contrast

### ISSUE THREAD

**Issue by nwanduka** [camicroscope/caMicroscope#1020]
**Describe the bug**
The report bug link in the page footer has low color contrast

**To Reproduce**
1. Go to 'Slides'
2. Right-click on the page
3. Click on 'Inspect'
4. Run the Axe DevTools a11y test
5. See error.

**Expected behavior**
Contrast between foreground and background colors should meet WCAG 2 AA minimum contrast ratio thresholds

**Screenshots**
![image](https://github.com/user-attachments/assets/c1f360d2-3f34-4c3c-9c1f-d292bf30d857)

**Comment by YashrajKupekar17** [comment]
I got it. Please assign it to me.i will solve it.
