### ISSUE TITLE
HTTP 404 attempting to load TileSource

### ISSUE THREAD

**Issue by 2grep** [camicroscope/caMicroscope#1037]
**Describe the bug**
caMicroscope viewer launches and fails to find TileSource for 5 seconds: in white in the background "Unable to open [object Object]: HTTP 404 attempting to load TileSource" and in black over the top "HTTP 404 attempting to load TileSource" then aborts back to SLIDE view (/apps/table.html)

**Selected lines from browser console**
Uncaught ReferenceError: module is not defined
    at DrawHelper.js:354:1

GET http://192.168.86.16:4010/img/IIP/raw/?DeepZoom=/images/CAP2014BP-01b.svs.dzi 404 (Not Found)
(anonymous) @ CaMic.js:175
Promise.then
loadImg @ CaMic.js:164
initCore @ init.js:197
(anonymous) @ init.js:130
setInterval
initialize @ init.js:125

**Following that 404'd URL**
Error opening '/images/CAP2014BP-01b.svs' with BioFormats, error loci.formats.FormatException: No IFDs found
loci.formats.FormatException: No IFDs found
	at loci.formats.in.MinimalTiffReader.initFile(MinimalTiffReader.java:470)
	at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:609)
	at loci.formats.FormatReader.setId(FormatReader.java:1466)
	at loci.formats.ImageReader.setId(ImageReader.java:863)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:660)
	at loci.formats.Memoizer.setId(Memoizer.java:726)
	at org.camicroscope.BFBridge.BFOpen(BFBridge.java:218)

**To Reproduce**
1. Reformat machine, install Ubuntu, install Docker, install Distro per directions
2. Visit caMicroscope site on local intranet
3. Upload batch of 24 slides, check all slides, note 3 green checks on all slides. Click done
4. Visit SLIDES
5. On any slide, click Open

**Expected behavior**
Slide viewer opens and starts rendering tiles

**Server (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS server
 - Hardware: The server is an HP Proliant DL160 Gen 9 with 500 GB of storage

**Desktop**
 - OS: MacOS Sonoma 14.5
 - Browser: Chrome
 - Version:  129.0

**Additional context**

**Comment by birm** [comment]
Thank you for reaching out.
This _could_ be a ARM/x86_64 issue, which would explain the ubuntu/macos difference for tileserver behavior. 

Can you tell me a little bit about the svs files? It's surprising to me that it's returning bioformats error traces over openslide. The logic for that is here (https://github.com/camicroscope/iipImage/blob/10e6732bfc2aba926be73f42f00ec7728523758f/iipsrv/src/IIPImage.cc#L128) and usually openslide can read svs files.

**Comment by 2grep** [comment]
Hmmm... there may be some operator error here. I got success with a batch of 2 files. The real issue may be that the workflow is not terribly transparent once you're in it, so it's hard to understand what's going on. For example, a per-file upload progress bar might be helpful.
