### ISSUE TITLE
broken pencil & freeline function

### ISSUE THREAD

**Issue by tdiprima** [camicroscope/caMicroscope#104]
Re: human markups #101 

Click pencil button on toolbar to enter a new annotation, left menu pops up with nothing in it.

**Comment by tdiprima** [comment]
I see a lot of `this.drawMarkups()` and `annotool.drawMarkups();` throughout the code base, but I do not see a function definition for `drawMarkups()`.

**Comment by birm** [comment]
drawMarkups is defined at https://github.com/camicroscope/caMicroscope/blob/dfbc7b89e1a0bdf601874c85459a72aa9f51f021/js/annotationtools/osdAnnotationTools.js#L423

**Comment by birm** [comment]
What is the result of the call made to api/Data/retrieveTemplate.php?

**Comment by tdiprima** [comment]
Was just going to say I found the function def.

this.annotools.drawMarkups() comes back as undefined in js/annotationtools/ToolBar.js.  And then we try to use it.  So the following error may not point to the actual error.  But to answer your question...

> What is the result of the call made to api/Data/retrieveTemplate.php?

It might not have gotten to that point.  You draw the rectangle, the left menu opens, and this error appears in the console:
```
Uncaught TypeError: Cannot read property 'properties' of undefined
    at formTree.<anonymous> (jsonform.js:2980)
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (underscore.js:76)
    at formTree.buildTree (jsonform.js:2978)
    at formTree.initialize (jsonform.js:2958)
    at init.$.fn.jsonForm (jsonform.js:3523)
    at Object.success (osdAnnotationTools.js:2987)
    at fire (jquery.js:3048)
    at Object.fireWith [as resolveWith] (jquery.js:3160)
    at done (jquery.js:8235)
```
