### ISSUE TITLE
Use templates properly

### ISSUE THREAD

**Issue by sharmaashish** [camicroscope/caMicroscope#116]
Our sliders should be templated. Here is an example of code that should have been templated. During our refactoring, we should be able to push the template into Mongo, and then populate the form from a separate file that relies on that template.
https://github.com/camicroscope/caMicroscope/blob/e7c690e140efdd1730352827ea3139508bae5c4e/js/annotationtools/osdAnnotationTools.js#L2414-L2622

**Comment by birm** [comment]
This is referring to templatizing dynamic services interactions, for future reference.

**Comment by birm** [comment]
See https://github.com/camicroscope/caMicroscope/blob/refactor/js/dataloaders.js; we're not hardcoding any templates with the refactor.
