### ISSUE TITLE
[Possible Bug] Draw tool allows for some self-intersecting polygons

### ISSUE THREAD

**Issue by pranavbudhwant** [camicroscope/caMicroscope#152]
While playing around with the draw tool, I was able to draw a self-intersecting polygon without the pop-up warning being displayed, I was able to recreate the situation a couple of times but am not able to narrow down the reason. 

![self-intersecting-polygon-](https://user-images.githubusercontent.com/23121515/54053264-b417a500-420c-11e9-84ee-886672b899c0.jpg)

**Comment by birm** [comment]
Hello, thanks for reporting! For some background, the restriction on self intersecting polygons is for accuracy of annotation measurements (e.g. area), which have algorithms that work for the case of simple polygons. The code for this alert is [here](https://github.com/camicroscope/caMicroscope/blob/d0d8ce279e3e792acbf1a46c041d8cf24491c964/core/extension/openseadragon-canvas-draw-overlay.js#L553) and the check code is [here](https://github.com/camicroscope/caMicroscope/blob/68480b43a419c80a56f4c31f08a79978f5c53357/common/util.js#L178). If you want to tackle this issue, fork, and put in a pull request. Let me know if you need any guidance with this.

**Comment by pranavbudhwant** [comment]
@birm Thanks, I'll try to solve this issue.

**Comment by birm** [comment]
I'm going to close this because it's a stale issue now, and I've had a hard time replicating it. Please re-open if you are either still interested in working with it, or have something you could give us to help replicate this (e.g. the annotation data json itself)
