### ISSUE TITLE
When a freeline drawing is very long, it won't be saved.

### ISSUE THREAD

**Issue by scotthoule** [camicroscope/caMicroscope#2]
When I drew a very long and complex freeline using the annotation tool, and tried to save it, an error popped up saying "wrong human secret". Is this because the length of the post message to php is limited?

**Comment by lastlegion** [comment]
If you see the apache logs:
`PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini.`

The quick fix is to change `max_input_vars` in php.ini to value of 50,000 or so.

The more sustainable solution would be to do some path simplification on the backend.

**Comment by sharmaashish** [comment]
@lastlegion why don't we deploy the [path simplification library](http://mourner.github.io/simplify-js/) when we are creating the annotation. Do this in the browser. Should be easy to add and can be something we can turn on/off
