### ISSUE TITLE
Support filenames with strange characters

### ISSUE THREAD

**Issue by LucaCinquini** [camicroscope/caMicroscope#20]
I noticed that when ingesting images with strange filenames, such as:
EX10-0218-4-CK8~18-[Boon's]-AV.svs
EX10-0218DV-1-[NBF]-CK8~18-AV.svs
the QUIP viewer wouldn't display the images. If I first renamed the files to something more standard, then QUIP would work just fine.

**Comment by lastlegion** [comment]
The issue seems to be with Openseadragon. 
```
Uncaught SyntaxError: Invalid regular expression flags
    at $.Viewer.open (openseadragon.js:4877)
    at osdCamicroscope.php:135
```

Looking more into it

**Comment by lastlegion** [comment]
I have filed an issue with OpenSeaDragon: https://github.com/openseadragon/openseadragon/issues/1188. 

For now I'm fixing the openseadragon that we ship with camicroscope. I'll look into filing a pull request with openseadragon later this week.

**Comment by lastlegion** [comment]
Fixed in: https://github.com/camicroscope/caMicroscope/commit/e70da0ed88de5a0cea846faa3b7d702b3e94c81b
Will be part of the next release.

**Comment by LucaCinquini** [comment]
Great, thank you.
Luca

On May 9, 2017, at 12:04 PM, Ganesh Iyer <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed in: camicroscope/caMicroscope@e70da0e<https://github.com/camicroscope/caMicroscope/commit/e70da0ed88de5a0cea846faa3b7d702b3e94c81b>
Will be part of the next release.

**Comment by lastlegion** [comment]
I have a filed a pull request with openseadragon too. Hopefully they'll merge it: https://github.com/openseadragon/openseadragon/pull/1189

**Comment by lastlegion** [comment]
My pull request got accepted in openseadragon https://github.com/openseadragon/openseadragon/pull/1189
So this will be a part of their next release too. Thanks @LucaCinquini for reporting.
