### ISSUE TITLE
'Remove button' for user-uploaded models

### ISSUE THREAD

**Issue by Insiyaa** [camicroscope/caMicroscope#213]
In model and segment app, there is no way to remove uploaded models. 
A _remove button_ would be good in model info table.

**Comment by animesh-007** [comment]
I would like to work on it.

**Comment by animesh-007** [comment]
Just for clarification, you want a remove button here 
<img width="439" alt="Screen Shot 2020-02-25 at 12 50 10 PM" src="https://user-images.githubusercontent.com/53366877/75224058-cd26b680-57cd-11ea-89f1-9b3b74a60983.png">

**Comment by Insiyaa** [comment]
That is for the slides, try looking into `segment` and `model` in apps.

**Comment by animesh-007** [comment]
I guess we are talking about here 
<img width="438" alt="Screen Shot 2020-02-26 at 1 44 55 AM" src="https://user-images.githubusercontent.com/53366877/75283860-a1411a80-5839-11ea-92a1-cdcaa3e4bbca.png">

**Comment by chinzhiweiblank** [comment]
Good Day, I managed to add a button to remove the model and delete the key from the IDB. Can I open a PR for review? There are some issues with the feature that I also wish to clarify.

**Comment by Insiyaa** [comment]
Yes, please go on with the PR. Feel free to ask if you have any doubts.

**Comment by Insiyaa** [comment]
closed with #223
