### ISSUE TITLE
Using IIPImage server with openseadragon

### ISSUE THREAD

**Issue by danielshamir** [camicroscope/caMicroscope#214]
I have the IIPImage server running and I am trying to display a deepzoom image but fail

This is how I am doing it :

var tileSource = {
            Image: {
                xmlns: "http://schemas.microsoft.com/deepzoom/2008",
                Url: "http://127.0.0.1/fcgi-bin/iipsrv.fcgi?DeepZoom=E:/DeepZoomFile/10580_12079_1121935_stitch_files/",
                Format: "jpg",
                Overlap: "2",
                TileSize: "256",
                Size: {
                    Height: "38290",
                    Width:  "17953"
                }
            }
        }; 

And the important line is :

Url: "http://127.0.0.1/fcgi-bin/iipsrv.fcgi?DeepZoom=E:/DeepZoomFile/10580_12079_1121935_stitch_files/"

I am getting errors from the browser that "fail to load tile image"

Any help or example of how should I do it ?
Thanks

**Comment by birm** [comment]
Hello, and thank you for the issue report. Can you tell me a bit about how you're running caMicroscope?

**Comment by danielshamir** [comment]
Hello
Thank you for your reply
I am not running caMicroscope but openseadragon and I believe that using the IIPImage server should be the same way as in caMicroscope So I hope that you can help me a bit.
My other option is to move to caMicroscope 

ThanksDaniel 

    On Thursday, 9 January 2020, 18:03:29 GMT+2, Ryan Birmingham <notifications@github.com> wrote:  
 
 
Hello, and thank you for the issue report. Can you tell me a bit about how you're running caMicroscope?

**Comment by birm** [comment]
thank you for your reply. This is a little out of scope for this project, but I'll do my best to help you anyway.
Have you tried using the .dzi link that iipImageServer provides, probably "http://127.0.0.1/fcgi-bin/iipsrv.fcgi?DeepZoom=E:/DeepZoomFile/10580_12079_1121935_stitch.dzi" ?

If this is not helpful, you may find more useful information from the [openseadragon repository](https://github.com/openseadragon/openseadragon/issues), or possibly from [iipimageserver](https://sourceforge.net/projects/iipimage/support) if you believe that this is due to your image file being read incorrectly.  
In either case, it's probably useful to describe what 10580_12079_1121935_stitch is, and any specific failed network calls that your browser is experiencing. If you believe that it's an iip serve issue, check the server logs too.

Good luck.

**Comment by danielshamir** [comment]
Thank you . I will cheack it.
Sent from Yahoo Mail on Android 
 
  On יום ה׳, ינו׳ 9, 2020 at 22:40, Ryan Birmingham<notifications@github.com> wrote:   
thank you for your reply. This is a little out of scope for this project, but I'll do my best to help you anyway.
Have you tried using the .dzi link that iipImageServer provides, probably "http://127.0.0.1/fcgi-bin/iipsrv.fcgi?DeepZoom=E:/DeepZoomFile/10580_12079_1121935_stitch.dzi" ?

If this is not helpful, you may find more useful information from the openseadragon repository, or possibly from iipimageserver if you believe that this is due to your image file being read incorrectly.
In either case, it's probably useful to describe what 10580_12079_1121935_stitch is, and any specific failed network calls that your browser is experiencing. If you believe that it's an iip serve issue, check the server logs too.

Good luck.

**Comment by danielshamir** [comment]
Hi 
The folder E:/DeepZoomFile/10580_12079_1121935_stitch_files contains all the folders that contains all the tile images
Here are some screens
The upper view :

And drill down to folder 11



Can you send me an example of how a call to a deepzoom file is mage using IIPImage server in caMicroscope please ?
Many thanks for your helpDaniel



    On Thursday, 9 January 2020, 22:40:11 GMT+2, Ryan Birmingham <notifications@github.com> wrote:  
 
 
thank you for your reply. This is a little out of scope for this project, but I'll do my best to help you anyway.
Have you tried using the .dzi link that iipImageServer provides, probably "http://127.0.0.1/fcgi-bin/iipsrv.fcgi?DeepZoom=E:/DeepZoomFile/10580_12079_1121935_stitch.dzi" ?

If this is not helpful, you may find more useful information from the openseadragon repository, or possibly from iipimageserver if you believe that this is due to your image file being read incorrectly.
In either case, it's probably useful to describe what 10580_12079_1121935_stitch is, and any specific failed network calls that your browser is experiencing. If you believe that it's an iip serve issue, check the server logs too.

Good luck.

**Comment by birm** [comment]
Deep zoom images usually have a document which describes the contents of the folder. This is usually something like a [xml ](http://openseadragon.github.io/example-images/highsmith/highsmith.dzi) or [jsonp](https://openseadragon.github.io/example-images/highsmith/highsmith.js). You can see the corresponding[ opsenseadragon documentation](https://openseadragon.github.io/examples/tilesource-dzi/) regarding this. Using this in the url is probably the simplest way to get this working, and it's usually how we do it in caMicroscope.
Alternatively you could describe each file's location as a custom function, as seen in [this example](https://openseadragon.github.io/examples/tilesource-custom/).

**Comment by danielshamir** [comment]
Thank you.
What i meant is an example of using iipimage server
ThanksDaniel

Sent from Yahoo Mail on Android 
 
  On יום א׳, ינו׳ 12, 2020 at 17:29, Ryan Birmingham<notifications@github.com> wrote:   
Deep zoom images usually have a document which describes the contents of the folder. This is usually something like a xml  or jsonp. You can see the corresponding opsenseadragon documentation regarding this. Using this in the url is probably the simplest way to get this working, and it's usually how we do it in caMicroscope.
Alternatively you could describe each file's location as a custom function, as seen in this example.

**Comment by birm** [comment]
We primarily use a modified version of iipimageserver to host openslide-compatible whole slide images. You can see our openseadragon open call [here](https://github.com/camicroscope/caMicroscope/blob/ab931b101cb7801281b738e577b44768bc235898/core/CaMic.js#L200).
I'm not sure if caMicroscope is the best example to help you with your problem though. Do you see anything at "http://127.0.0.1/fcgi-bin/iipsrv.fcgi?DeepZoom=E:/DeepZoomFile/10580_12079_1121935_stitch.dzi"?

**Comment by danielshamir** [comment]
Thank you very much !!

Sent from Yahoo Mail on Android 
 
  On יום א׳, ינו׳ 12, 2020 at 19:33, Ryan Birmingham<notifications@github.com> wrote:   
We primarily use a modified version of iipimageserver to host openslide-compatible whole slide images. You can see our openseadragon open call here.
I'm not sure if caMicroscope is the best example to help you with your problem though. Do you see anything at "http://127.0.0.1/fcgi-bin/iipsrv.fcgi?DeepZoom=E:/DeepZoomFile/10580_12079_1121935_stitch.dzi"?

**Comment by birm** [comment]
Ok. I'll close this issue. Please reopen it if you still have more questions on this topic.
