### ISSUE TITLE
Memory info of the model

### ISSUE THREAD

**Issue by Insiyaa** [camicroscope/caMicroscope#215]
It would be helpful to know the memory consumptions of the model to prevent overloading while using the same model in caMicroscope on another machine.

An additional field could be added to the model info table showing the maximum memory used of all trials.

Hint: [Performance section](https://js.tensorflow.org/api/1.5.2/#Performance) of tfjs documentation.

**Comment by divyaprabha123** [comment]
Hi @Insiyaa Can I raise a PR for this Issue?

**Comment by Insiyaa** [comment]
Yes, go for it!
