### ISSUE TITLE
Lack of "Drag and Drop file to open feature" in the application

### ISSUE THREAD

**Issue by mjgupta** [camicroscope/caMicroscope#218]
**Lack of a drag and drop feature to open a file**
[](url)
- It would be great if we can provide a drag to open file functionality in caMicroscope application like other modern image editing/annotation software, so that a user can drag an image file he wants to open, from one active window to the caMicroscope application to open it.

- [Here is a demonstration in Microsoft Paint](https://gfycat.com/favoritedetailedafricanclawedfrog) 
- [And here is another demonstration](https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/8a415e72-c17f-4cc3-9b64-1c3ab14cf82c/uploader-preview.gif)

- Improved User Experience : It would save a user from the hassle of navigating through the entire file path and would ease the process of opening an image in the caMicroscope application.

I have started working on the issue and would be pushing the code soon!

**Comment by mjgupta** [comment]
#220 Added the feature, with basic CSS styling and changes in loader.html and loader.js files.
Please have a look , and suggest any suitable changes.

**Comment by amritansh22** [comment]
@birm I think this should be closed now.

**Comment by birm** [comment]
Yes, good catch.
