### ISSUE TITLE
Removing the 'open' button if 'NO DATA'

### ISSUE THREAD

**Issue by zengchu2** [camicroscope/caMicroscope#224]
When I open 'table.html' locally, I found there is an open button in the list as the screenshot shows.
![微信图片_20200302054921](https://user-images.githubusercontent.com/32441682/75664880-97f4eb00-5c49-11ea-8836-d942def404fc.png)
I think the button is unecessary if there is no data available.

I have managed to disable the button if there is no data, let me know if I should open an PR to address this enhancement.

**Comment by birm** [comment]
This could be replaced with a link to the image loading page, re https://github.com/camicroscope/Distro/issues/97

**Comment by birm** [comment]
closed with #226
