### ISSUE TITLE
Additional Memory being allocated every time Prediction is done

### ISSUE THREAD

**Issue by leoarc** [camicroscope/caMicroscope#228]
When the predict feature is used on the same slide using same model , each time a new area is selected and Prediction is done new memory(tensors) is allocated . Thus after a few number of predictions the memory is maxed out . 

![Selection_003](https://user-images.githubusercontent.com/32388846/76152580-1b4d8b00-60e7-11ea-85b8-1c51dc04f750.png)

@Insiyaa @birm  How do we measure the memory consumption of the model ? ( To add it to  ``` model info ``` table for issue #215 as with every trial the memory consumption increases )

**Comment by Insiyaa** [comment]
You can clean up intermediate allocations using [tf.tidy](https://js.tensorflow.org/api/latest/#tidy).

**Comment by leoarc** [comment]
Can you give more information on what allocations I need to ``` dispose``` ?  I tried enclosing the call to the  ``` runPrecict( ) ``` in  ``` tf.tidy() ``` which wasn't helpful. 

Some of my observations are :

- When a new area is selected for prediction a fixed number of new tensors( say x ) are allocated(In the above case x = 8)

-  If the selected area is large and is divided into batches for prediction , then no. of new tensors = (no. of batches * x ).

**Comment by Insiyaa** [comment]
I believe you need to enclose the block inside the for loop [here](https://github.com/camicroscope/caMicroscope/blob/17552ad812932e7fdbe13e0a2f8c3ddc5113d483/apps/model/model.js#L504). The allocation for each patch happens here, so disposing of those will reduce memory consumption; please keep me updated.
No, extra memory shouldn't be allocated - it was on the to-do list, thanks for looking into this:)

**Comment by leoarc** [comment]
``` tf.tidy() ``` cannot contain any ``` async() ``` functions  .  So we cannot use it to enclose our code as ``` model.predict ``` is  asyncrhonous . So we have to take care of disposing all tensors ourselves.
Also every time we broadcast a tensor , two instances of a tensor are created which also causes additional tensors.

I will open a PR soon to fix this .

**Comment by birm** [comment]
Just as a summary for any brave people in the future, @leoarc fixed _most_ of this in #231 but found that in https://github.com/camicroscope/caMicroscope/blob/17552ad812932e7fdbe13e0a2f8c3ddc5113d483/apps/segment/segment.js#L768 that there may be unresolved issues related to https://github.com/tensorflow/tfjs/issues/264

**Comment by AbdulRashidReshamwala** [comment]
@birm  I think this issue can be closed
