### ISSUE TITLE
error in caMicroscope/test/extension/slideId.js

### ISSUE THREAD

**Issue by darkCavalier11** [camicroscope/caMicroscope#235]
**Describe the bug**
i was going through the extension in test directory where i found the `zoom-to-location-test.html` file which have multiple `css`  and `js` file loading error for invalid location. i fix those but i found  a invalid url in `slideId.js`.

**To Reproduce**
Steps to reproduce the behaviour:
open the `zoom-to-location-test.html` in browser and error due to fetch will be in the console.

**Expected behaviour**
The url should be a proper http/s url for fetch api to work while this case url is a relative one.

**Screenshots**
the url is 

> /data/Slide/find?slide=

![Screenshot from 2020-03-12 21-58-34](https://user-images.githubusercontent.com/57953014/76545348-9f20c200-64af-11ea-8168-8dcba8c5a0b7.png)

the error in browser after fixing some bug is:
![Screenshot from 2020-03-12 22-23-17](https://user-images.githubusercontent.com/57953014/76545599-16eeec80-64b0-11ea-88bd-64e760fd505e.png)

**Additional context**
i tried to resolve by adding multiple possible parts to make the url complete but it didn't work. plz help.

**Comment by viditvarshney** [comment]
That not seem to be an error, According to you there is an error in this URL, 
`ifrm.src = '/viewer.html?slideId=' + id;` 
but this depends on the particular slide id, see the particular id is concatenated with URL to open that slide 
**For the demo you can build the project and run on your local machine**

**Comment by birm** [comment]
I ... don't remember what this is for. I suspect it may be left over from another testing strategy. @tdiprima may remember better than I do.

**Comment by tdiprima** [comment]
Hi @birm & @darkCavalier11  The `test` folder is old news.  You can delete it.

**Comment by birm** [comment]
closed with https://github.com/camicroscope/caMicroscope/commit/83cb9ae78a4abd7d92245663623a1a5ced948908
