### ISSUE TITLE
SIGNUP Option in the landing page

### ISSUE THREAD

**Issue by viditvarshney** [camicroscope/caMicroscope#238]
I took a quick look at caMicroscope, and found that there is no option for signup
This would be nice if there is an option for the Signup
The signup option on the landing page would be useful for the user. The user will be redirected to the signup page

**Comment by viditvarshney** [comment]
what you say @birm @nanli-emory

**Comment by Girrajkishor** [comment]
I agree with you sir as we discussed on channel, there are other commits as well

**Comment by viditvarshney** [comment]
thank you
