### ISSUE TITLE
Minimize Hosted Files

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#240]
As it is now, since the packaging concept didn't take off, parcel is an appendix. So, I see there being two options; use parcel to its full potential on each of the apps, and host that (multi stage build), or alter the file paths slightly as to not need packages, and just use an apache container.

**Comment by nanli-emory** [comment]
We should keep using Parcel~~~!!!

**Comment by animesh-007** [comment]
@birm  I would like to work on this with you can I get some advice on this?

**Comment by birm** [comment]
Thanks for your interest. I've done some version of this with #243, but I had a hard time getting parcel to work properly on building the entire thing. If you'd like, we'd highly welcome a PR which does a build on each of the apps in ./apps (and probably just copy over ./index.html since it's just a redirect), and hosts _that_. We're not _super_ picky on how you choose to accomplish this technology wise. Especially considering that there's now no reason to use all of the features of parcel; maybe a minifier makes more sense?
