### ISSUE TITLE
Labeling tool slow after 300 labels on a single slide

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#242]
@ebremer please provide more context

**Comment by ebremer** [comment]
When starting the labeled annotation of a fresh image, things work well til about 300 annotations when the UX will start to slow down.  Moving to a new image, the speed will be good again until ~300 annotations is reached again.

**Comment by viditvarshney** [comment]
sir ~300 annotations on a single image is usually not present although, A image with 300 labels is more than enough to point, is there a need for enhacement ?
 just for clarification

**Comment by ebremer** [comment]
we are doing greater than 300 annotations per image.  We would need an enhancement.

**Comment by birm** [comment]
This may or may not be explained by the labeling tool prototype adding a separately tracked layer for each item. This was done so that users could zoom into each annotation, but the overhead does grow quickly.
