### ISSUE TITLE
Missing Ability to upload files

### ISSUE THREAD

**Issue by AbdulRashidReshamwala** [camicroscope/caMicroscope#248]
**Bug**
commit 39d2d683dc73619190b3f8b57d8f69272dbfcb63 seems to have removed apps/loader/loader.html which was the primary way to upload files is there another way to upload files or was it removed by mistake
**To Reproduce**
 Going to 'http://localhost:4010/apps/loader/loader.html' errors out.

**Expected behavior**
Show the uploading UI

**Screenshots**
![Screenshot from 2020-03-25 20-31-40](https://user-images.githubusercontent.com/47809786/77551037-d774c700-6ed7-11ea-8cbc-f1faf3ef73de.png)

**Comment by AbdulRashidReshamwala** [comment]
There was a bug in apps/table.html which removed the ability to upload data 
please check and merge https://github.com/camicroscope/caMicroscope/pull/249

**Comment by birm** [comment]
Thanks for the fix!
