### ISSUE TITLE
Incorrect email validation

### ISSUE THREAD

**Issue by mgautam98** [camicroscope/caMicroscope#257]
**Describe the bug**
The regex used to validate email does not work even on trivial mistakes.
e.g when I type a@@b.com, a@@b@.com, a@b.com; etc many more are there

**To Reproduce**
Simply type above-mentioned email when prompted on the signup screen

**Expected behaviour**
Validation should fail

**Screenshots**
![Annotation 2020-03-27 051929](https://user-images.githubusercontent.com/29784549/77707854-6bd04e00-6fec-11ea-94f6-bb32b5eee020.png)

**Comment by mgautam98** [comment]
Hey, @birm just noticed that all the spellings of behaviour in the bug report template are wrong. Where to find them?

**Comment by birm** [comment]
behavior/behaviour is a regionalism, neither is wrong. If you insist on changing it, see the camicroscope/.github repo
