### ISSUE TITLE
Finish Cleaning up style

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#274]
To get the CI build to work, we've added some ignore rules to eslint. Let's work to remove as many as we feel are reasonable.

- [x]     "camelcase" : 0,
- [x]     "no-var" : 0,
- [x]     "prefer-promise-reject-errors" :0,
- [x]     "no-extra-bind" : 0,

**Comment by cjchirag7** [comment]
@birm , may I work on this ? I feel that we can remove most of these.

**Comment by cjchirag7** [comment]
@birm , we are still ignoring the 'no-var' rule , shall we remove this also ?

**Comment by birm** [comment]
I think it's fine for now.
