### ISSUE TITLE
UI Loader - only post if check successful

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#286]
We have a number of slides added to camicroscope.org which are just broken, and I think this is the culprit.

**Comment by mgautam98** [comment]
@birm I would like to work on this issue.

**Comment by mgautam98** [comment]
In the handlecheck method we are only checking filename and id, if sucessful we are changing the status. While in the handlepost we are actually storing all info e.g mmp_x, mmp_y in store.

But in the application when we click on the checkbtn it shows us all the information with preview, mmp_x, mmp_y etc. So, I am a bit confused.

**Comment by cjchirag7** [comment]
@birm , one more problem is that whenever user presses the 'Post' button multiple times, multiple slides with same details are generated. 
**Screencast**
![upload-table-old](https://user-images.githubusercontent.com/45796806/78421781-fb729e00-7677-11ea-93e5-76939d4271a3.gif)

I have fixed this and many other problems and resolved this issue in #313 , please review.

**Comment by birm** [comment]
:tada:
