### ISSUE TITLE
Pure form --  document.registerElement is deprecated and will be removed in M73

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#290]
Chrome -- ```pure-form.js:2277 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
(anonymous) @ pure-form.js:2277
(anonymous) @ pure-form.js:2283```

**Comment by AbdulRashidReshamwala** [comment]
@birm the pure form library is not maintained anymore should we replace it with somthing else?

**Comment by birm** [comment]
I think that leaves the easier options to use a polyfill or update it ourselves. I'm sure this will be bumped in priority when a major browser actually removes the functionality :wink:

**Comment by cjchirag7** [comment]
@birm , I think we are already using the polyfill in document-register-element.js but that was too old, so I have updated it.
