### ISSUE TITLE
Page for available slides should be mobile-responsive [UI Enhancement]

### ISSUE THREAD

**Issue by cjchirag7** [camicroscope/caMicroscope#293]
**Is your feature request related to a problem? Please describe.**
Due to the large table, the page for available slides is not mobile-responsive and doesn't look good on small screens

**Describe the solution you'd like**
The view on small screen appears like this :
![earlier-mobile-view](https://user-images.githubusercontent.com/45796806/78213249-bf9cd480-74cf-11ea-8eb3-0c39303a91ea.png)

**Describe alternatives you've considered**
The table can be made scrollable, for small screens.

**Additional context**
This can be easily fixed by using Bootstrap classes.

**Comment by birm** [comment]
closed with #294
