### ISSUE TITLE
The check slide table in upload modal is not responsive 

### ISSUE THREAD

**Issue by cjchirag7** [camicroscope/caMicroscope#305]
**Is your feature request related to a problem? Please describe.**
The table of slide, which user gets after clicking on 'Check' button, after uploading slide, is not responsive
It appears as follows -
![upload-table-old](https://user-images.githubusercontent.com/45796806/78372692-37a9ee00-75e7-11ea-8edb-21e18ffd55a0.gif)

**Describe the solution you'd like**
The table can be made responsive by enclosing it inside a div with bootstrap class 'table-responsive'

**Comment by birm** [comment]
Closed by #306
