### ISSUE TITLE
Heatmap Updates don't seem to store color/gradient info.

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#307]
**Describe the bug**
Editing heatmap colors/bins does not reflect, instead only two bins of green are seen.

**To Reproduce**
Edit a heatmap and its colors

**Expected behavior**
Data in DB reflects color/bin changes

update data query body like: ```{"provenance.analysis.fields":[{"name":"necrosis","range":[0,1],"value":[0,1]},{"name":"tumor","range":[0,10],"value":[0,10]}],"provenance.analysis.setting":{"mode":"gradient","field":"necrosis"}}```

**Comment by cjchirag7** [comment]
I would like to work on this.

**Comment by Hemansh31** [comment]
@cjchirag7 are you working on this?

**Comment by cjchirag7** [comment]
Currently I have not started working on this.
You may work on this, if you like :)

**Comment by cjchirag7** [comment]
@Hemansh31 , I'm starting to work on this. Please tell, if you are still interested.

**Comment by birm** [comment]
:tada:
