### ISSUE TITLE
Data Utility for annotation

### ISSUE THREAD

**Issue by AbdulRashidReshamwala** [camicroscope/caMicroscope#316]
I have started to work on a dataset parser converts data from multiple slides and converts it into one dataset 
[code](https://github.com/AbdulRashidReshamwala/data-parser-caMicroscope)
[Hosted version](https://agile-garden-55713.herokuapp.com/)
Let me know if you have any issues or feature request
The tool currently uses the notes section of slide for determining the class

**Comment by birm** [comment]
That's pretty cool; I'll bring it to @nanli-emory 's attention :+1:

**Comment by AbdulRashidReshamwala** [comment]
@nanli-emory @birm  Is there any changes you think that are necessary and what are the steps to incorporate with entire system should I make a docker Image exposing this functionality as an api or should it be a complete separate project
