### ISSUE TITLE
Error 'Unexpected end of input' at response.json() in function checkUserPermissions()

### ISSUE THREAD

**Issue by cjchirag7** [camicroscope/caMicroscope#320]
**Describe the bug**
When opening the slides table (table.html), the below error is shown in console -
```
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at table.html:494
```

**To Reproduce**
1. Go to 'Slides' (table.html)
2. Open console in your browser

**Expected behavior**
This error should not occur. 

**Screenshots**
![Screenshot from 2020-04-05 15-52-39](https://user-images.githubusercontent.com/45796806/78472356-a3aa6480-7755-11ea-9e91-efdd82c16fd5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Comment by birm** [comment]
:tada:
