### ISSUE TITLE
File already exists error even after the slide is deleted.

### ISSUE THREAD

**Issue by akhil-rana** [camicroscope/caMicroscope#324]
**Describe the bug**
`File with name 'sample.svs' already exists` error is shown even if the file was previously deleted from the slide table

**To Reproduce**
1. Upload a slide
2. Delete the same slide from slides table
3. Now try to re upload the same file without changing file name.

**Screenshots**
![ezgif-5-6d66c347e9ab](https://user-images.githubusercontent.com/36575628/78514869-4227db80-77d1-11ea-97f9-464956f3e27c.gif)

**Desktop :**
 - OS: Ubuntu 
 - Browser: Chrome

**Comment by cjchirag7** [comment]
I think, when deleting a slide, the file is not deleted at the backend, only the data is deleted from the DB. Due to this, this might happen.

**Comment by akhil-rana** [comment]
Yes, I think so too.
@birm Any thoughts?

**Comment by birm** [comment]
Yes. There's a separation between slides existing on the fs and being registered in the db. Our slide process is pretty confusing.

**Comment by akhil-rana** [comment]
Okay, any suggestions on how to delete from fs?

**Comment by Vedant1202** [comment]
Hi @birm and @akhil-rana, I think [#341 ](https://github.com/camicroscope/caMicroscope/pull/341) and [#25](https://github.com/camicroscope/SlideLoader/pull/25) should fix this.

**Comment by cjchirag7** [comment]
I think [#23](https://github.com/camicroscope/Caracal/pull/23) is a better fix, as it takes care that when the slide is deleted from the DB, then only the file is deleted locally, and keeps the route secure as earlier.
[#25](https://github.com/camicroscope/SlideLoader/pull/25) has some major problems with the route security, which I have commented on the PR. These should be looked carefully, before performing any merge.

**Comment by akhil-rana** [comment]
@birm 
Should this be closed?
