### ISSUE TITLE
Slide table not refreshed when uploading first slide

### ISSUE THREAD

**Issue by Vedant1202** [camicroscope/caMicroscope#337]
**Describe the bug**
When we upload the first slide, the table containing slides is not being seen. 

**To Reproduce**
1. Clear the entire database.
2. Go to upload slides page.
3. Upload a slide.

**Expected behavior**
The table should be seen containing the uploaded slides. This is not being seen because the table does not exist in the DOM and we've not added a condition to add it.

**Screenshots**
1. Clear database and go to upload slide
![Capture1](https://user-images.githubusercontent.com/35070972/78649955-d4b4a180-78db-11ea-9e78-587327b4ac37.PNG)
2. Upload a slide
![Capture2](https://user-images.githubusercontent.com/35070972/78649993-eac26200-78db-11ea-965b-89690b3c58ae.PNG)
3. No table visible.
![Capture3](https://user-images.githubusercontent.com/35070972/78650113-15141f80-78dc-11ea-944f-fdd116becc65.PNG)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 72.0.2

**Comment by Vedant1202** [comment]
This is fixed in PR [#338 ](https://github.com/camicroscope/caMicroscope/pull/338).

**Comment by cjchirag7** [comment]
Actually, if you look in the browser console, this error is shown -
```
table.html:425 Uncaught (in promise) RangeError: Invalid array length
    at table.html:425
```

**Comment by birm** [comment]
Ah, this was my bad. Thanks for the fix(es)!
