### ISSUE TITLE
Filename can't contain spaces when uploading [BUG]

### ISSUE THREAD

**Issue by cjchirag7** [camicroscope/caMicroscope#343]
**Describe the bug**
When uploading a slide with filename containing spaces, the preview is not available, due to which 'check' fails and user is not able to post the slide.

**To Reproduce**
1. Go to 'Upload' button on 'Slides' page
2. Upload any file and enter the new filename with spaces eg. 'my new file.svs'
3. Click on 'Finish Upload'
4. Click on 'Check'

**Expected behavior**
Either user must be able to create filename with spaces, or the spaces should automatically be converted to '_' to avoid any bug

**Screencast**
![filename_with_space](https://user-images.githubusercontent.com/45796806/78706232-5df3c480-792c-11ea-8b0e-8f10d5727ea2.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version  80.0.3987.132 (Official Build) (64-bit)

**Comment by birm** [comment]
Thanks for the fix via #344
