### ISSUE TITLE
Consider option: less direct links between slides and data products

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#350]
This is a discussion, not a call to implement.
It's kind of silly when adding external results to have to perform a step which aligns the markup/heatmap data to the slide uuid. We used to configure the findX for those in store to perform a search based both on the uuid and the name-study-specimen triple.
Do we want to add that back?

**Comment by Hemansh31** [comment]
We can but how would it be better than what we currently have?

**Comment by birm** [comment]
It would allow us to work with cases where we know the slide's identifying human readable information, but not its uuid.
Though, this is pretty much only for loading results to existing images as part of a collection. Maybe the hypothetical loader in #352 would do the lookup on load, which would be preferable to checking in to api calls (one by uuid, one by params) each time
