### ISSUE TITLE
Batch Slide Loader App

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#352]
In short, a ui-based way to add a bunch of slides.
How do we want to do this?

**Comment by birm** [comment]
In this situation, we've typically used manifests used via shell (see slideutil in the slideloader repo) but we've been discussing something like this for a while, off and on

**Comment by leoarc** [comment]
We can use the existing process and allow multiple file uploads but reduce the number of inputs taken from the user like : 

- Take a shared file name such as "Cancer_Slides" and then index it and name all the slides 

- There is already a talk about the filename randomizing feature which will remove that field

- Then we can have one set of buttons : ``` Finish ```  which shows which slides are valid , ```  Check ``` to see the preview and details of these slides in the table below and ``` Post ``` to post these ones .

Probably with increase in number and size of slides this will become less efficient .

**Comment by birm** [comment]
Thinking out loud, it'd be cool if this worked with result files too, such as heatmaps and segmentations/annotations...

**Comment by cjchirag7** [comment]
@birm , can you elaborate on how can we take the heatmap data and annotations etc. from user as input ? Or do we need to make give the user an option to upload a csv file containing manifests ?

**Comment by birm** [comment]
Things that it would be useful to add to the new batch slide loader:
- show source/original filename in a column
- let users manually edit destination filenames and slide names
- read a json or csv manifest mapping original filenames to other fields (e.g. slide name, study, filter, etc)

**Comment by akhil-rana** [comment]
What about we add a tooltip (or something like that) which shows the original file name on hovering the specific row?
Since more columns may lead to some UI discomfort (scrolling the tale horizontally) so I thought this may work.

and I'm already working on individual filename/slidename edit functionality.

**Comment by birm** [comment]
Closed by #385 and #389. Of course, further suggestions/additions are still welcome.
