### ISSUE TITLE
Search doesn't work on slides

### ISSUE THREAD

**Issue by cjchirag7** [camicroscope/caMicroscope#355]
**Describe the bug**
When user tries to search the slides with any keyword, the search doesn't work correctly and a strange behaviour is shown

**To Reproduce**
1. Go to Slides page
2. In the search input, type any keyword

**Expected behavior**
Appropriate search results should be shown, along with the change in pagination, as per the search results. 

**Screencast**
![buggy-search](https://user-images.githubusercontent.com/45796806/79061439-fa5ff300-7cad-11ea-9c00-aa5d906fa074.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 80.0.3987.132 (Official Build) (64-bit)

I have also tested it in Firefox, in my desktop, the behaviour is same.

**Comment by birm** [comment]
Fixed via #356
