### ISSUE TITLE
Sorting of slides doesn't work in Chrome (Desktop)

### ISSUE THREAD

**Issue by cjchirag7** [camicroscope/caMicroscope#357]
**Describe the bug**
No change in the order of slides when user clicks on the 'up' or 'down' arrow button in the table headers

**To Reproduce**
1. Go to Slides page.
2. Click on 'up' arrow, near the 'Name' field.

**Expected behavior**
The slides should get sorted in increasing order of their names

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Actually, this is due to **improper definition of the comparator function** , used to sort the elements. In JS, the comparator function must return a negative value, a positive value or 0, depending upon the comparison of the elements [ See [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) for reference ]. In the present code, the comparator function return a true or false value (Boolean) instead, which creates this bug.

**Comment by birm** [comment]
Fixed via #358
