### ISSUE TITLE
Cannot uplaod any model to the model app

### ISSUE THREAD

**Issue by leoarc** [camicroscope/caMicroscope#359]
For any model name the error  " model with same name exists please select new name "  appears . As a result no model can be uploaded .  Example :

![bug1](https://user-images.githubusercontent.com/32388846/79092694-4757ce00-7d6f-11ea-9cc2-966184dbd97c.gif)

**Comment by birm** [comment]
Oh, you're right. It looks like it's because namearray is never initalized. A moment...

**Comment by leoarc** [comment]
I think that is not the problem .It is because some old code was added in a PR which is caused the error . Fixed in #360

**Comment by birm** [comment]
closed via #360
