### ISSUE TITLE
Direct deletion of files for admins gives error

### ISSUE THREAD

**Issue by Vedant1202** [camicroscope/caMicroscope#368]
**Describe the bug**
Deletion of slide from admin account encounters error. This is due to overlooking of an edge case where the admin does not have a delete request associated with that file. Thus the api call should not happen.

**To Reproduce**
1. Login as admin
2. Delete slide
3. See error

**Expected behavior**
File should be deleted

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
![error](https://user-images.githubusercontent.com/35070972/79370527-78532100-7f70-11ea-9a79-e5d1d8b648c6.gif)

**Comment by Vedant1202** [comment]
Hi @birm, just review this quick fix, its something I overlooked in my previous PR, sorry for that.

**Comment by birm** [comment]
No worries; thanks for the catch and fix!
