### ISSUE TITLE
Slide name not updating in the table when the update is successful [BUG]

### ISSUE THREAD

**Issue by cjchirag7** [camicroscope/caMicroscope#373]
**Describe the bug**
When user updates the name of a slide, the slide name doesn't change until he reloads the page. This can be improved to automatically update the name.

**To Reproduce**
1. Go to the slides page
2. Click on the pencil icon, which appears when you hover over any of the slide names 
3. Click OK on alert showing successful update of file name.
4. Observe that slide name doesn't change
5. Reload the page to observe the change in the slide name.

**Screencast**
![bug](https://user-images.githubusercontent.com/45796806/79470191-bd359100-801e-11ea-82ce-c8f8eaabb361.gif)

**Expected behavior**
The user must not need to reload the page. The name of the slide should be updated automatically when the operation is successful.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 81.0.4044.92 (Official Build) (64-bit)

**Additional context**
This is actually due to the calling of intialise() function outside the promise. Instead, it should be called inside the promise to fix this.

**Comment by akhil-rana** [comment]
Well;
I did re-initialise the table when I added the feature but I don't know why it did not work in your case.

**Comment by cjchirag7** [comment]
Fixed by #372
