### ISSUE TITLE
Error finding slides

### ISSUE THREAD

**Issue by mgautam98** [camicroscope/caMicroscope#374]
**Describe the bug**
Because of some recent changes I can not access the previous uploaded slides and I am getting the following error. I can still access the info page and all the slides are listed there.

**To Reproduce**
1. fetch latest develop branch
2. Run 
3. Go to tables page

**Expected behavior**
It should list all the slides.

**Screenshots**
![image](https://user-images.githubusercontent.com/29784549/79477088-63859480-8027-11ea-8d22-4736baf5841f.png)

**Desktop (please complete the following information):**
 - OS: WIN 10 Pro
 - Browser Chrome

I don't know if I missed something. How do I fix it?

**Comment by birm** [comment]
Can you confirm that all of the services are up? If so, can you reload with the dev console network tab up, and see if any of those look wrong? (error code or malformed json). I'll try to replicate in the meantime.

**Comment by cjchirag7** [comment]
@mgautam98 , have you pulled the latest commits from SlideLoader repository (develop branch) and checkout `develop` branch  inside that repo . Similarly for Caracal repository and then, ran the commands `docker-compose -f develop.yml build loader` and `docker-compose -f develop.yml build back`  ?

**Comment by mgautam98** [comment]
@cjchirag7 I have pulled Caracal develop but not SlideLoader. Let me do that first.
Also all the services are running.

**Comment by birm** [comment]
Glad to hear! I'm still unsure what exactly was causing this issue, but glad it's resolved!
