### ISSUE TITLE
Extend Slide Filter to Results

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#387]
With the new backend, we have a filters concept (that is, users can be given a list of filters, and cannot see slides not in that list.) But what of annotations/etc?

Using the concept of "if you can see a slide, you can see everything associated with it" (at least for now), this could be accomplished by copying the filter field of a slide to annotations, etc on creation.
Open for discussion/complaints as needed.

**Comment by Priyaraj17** [comment]
May, I get some more information regarding this issue?

**Comment by Naseem010** [comment]
Hi @birm Can you please elaborate this issue ,i am getting some confusion regarding this issues.

**Comment by Sudesha-STR** [comment]
Hey @birm, may I get some more information on this issue?

**Comment by birm** [comment]
Closing as a stale issue. Feel free to reopen if you think this should be active still.
