### ISSUE TITLE
Documentation (and potentially fix) for Authentication Disable

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#40]
While most of the application has authentication simply in one place, simply uncommenting the session  key and user in authentication.php is not sufficient, in part due to a similar check in flextables index.

**Comment by lastlegion** [comment]
Yes it would be great if we could `require('../authenticate.php')`. I was having some issues with the [Slim Framework](https://www.slimframework.com/) when I tried.

**Comment by birm** [comment]
The other issue can be resolved with session_start(); being moved BEFORE the commented lines, as simple as that sounds.
