### ISSUE TITLE
UI Improvements/Fixes

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#41]
**General**

- [x] Universal Design Document/Spec for caMic and related apps
- [x] Header Redesign

**Image Loader**

- [x] “Problem with Uploading” should probably be bigger or have border/box
- [x] change 100% color on progress bar

**Feature Scape**

- [ ] Move where scatter plots are and/or show/hide the matrix on click.
- [ ] On hover, show mini plot if possible, else correlation coefficient.
- [ ] On click, show modal plot with correlation coefficient.

**caMicroscope**

- [ ] Image analysis button seems to change opacity of a non-visible div
- [ ] Make workflow on “work order panel” more apparent.
- [ ] Contextual (in place) menus/commands for annotation

**caMic Lymphocyte**

- [x] Having two home buttons makes no sense
- [ ] Blue plus and minus icons can’t be seen well
- [ ] There should be a way to exit draw thin line from the menu
- [ ] Zoom on scroll doesn’t seem to work, also can’t zoom out
- [ ] Plus and minus should be functionally replaced with an opacity slider, not two head buttons

**Comment by birm** [comment]
[Design Spec](https://docs.google.com/document/d/1d2rf_v5ITXrBOAdvzoH6DpbU5QBU_AU399pAN1hyrkk/edit?usp=sharing), In progress

**Comment by ajasniew** [comment]
Added a microscope icon and remove the home icon from the caMic Lymphocyte toolbar.
(https://github.com/camicroscope/caMicroscope/pull/44)

**Comment by birm** [comment]
Thank you; I've checked off the corresponding item.

**Comment by birm** [comment]
the redesigned header is now in the emory-dev branch of Security repo, and a screenshot can be seen in the "Header/Toolbar" of the [design spec](https://docs.google.com/document/d/1d2rf_v5ITXrBOAdvzoH6DpbU5QBU_AU399pAN1hyrkk/edit#heading=h.9xmy49wn4uq5). I welcome any and all suggestions.
