### ISSUE TITLE
Something confusing about the predict function of caMicrosope

### ISSUE THREAD

**Issue by 3048205169** [camicroscope/caMicroscope#411]
**Describe the bug**
This maybe my mistake but actually there is problem. There is always a caveat that the value of input patch size that I typed in is incorrect.

I used to learn machine learning but I was not so familiar with the image processing. Thus, I thought maybe I have missed something very important.

**To Reproduce**
Just type in information into the box.

**Expected behavior**
I have no idea what will be right in the screen but I know Mine is wrong.

**Desktop (please complete the following information):**
 - OS: Ubuntu as the server, Windows as the client
 - Browser chrome

Maybe someone could tell me what is the underlying mechanism of this function? (e.g. the model? the input? the output? the right way to use that model?)

**Comment by 3048205169** [comment]
![uploading model](https://user-images.githubusercontent.com/38618523/85242001-509c9f80-b470-11ea-8555-dddad62028a1.png)

**Comment by 3048205169** [comment]
![uploading model](https://user-images.githubusercontent.com/38618523/85242174-d91b4000-b470-11ea-8b25-346d40f747eb.png)
![model input](https://user-images.githubusercontent.com/38618523/85242212-f18b5a80-b470-11ea-989c-87e77b9006ae.png)

**Comment by leoarc** [comment]
caMicroscope uses ``` tensorflow.js ``` models for classification and segmentation . Some example models can be found [here](https://github.com/camicroscope/tfjs-models) . 

The input patch size is the size of patches on which the model was trained .
For example , for [this](https://github.com/camicroscope/tfjs-models/tree/master/Classification%20Sample%20Models/classification-of-HnE-stained-histological-breast-cancer-images) model the input patch size should be 512 , the classes should be benign, normal, insitu and invasive and the format should be RGB . 

The normal workflow for uploading a model is something like : 

- fill in the details as mentioned above.
- Upload the tfjs model: The first upload is for the model.json file and the next one is for all the binaries. For the example above all files are present [here](https://github.com/camicroscope/tfjs-models/tree/master/Classification%20Sample%20Models/classification-of-HnE-stained-histological-breast-cancer-images/tfjs_model) .
- Once uploaded [this](https://docs.google.com/document/d/127LIvqi_f3QzYQNYDXJm83AWVhq56igG4HpVa5xy-FM/edit#heading=h.nrnw03t7conb) is a guide that can help for using the Predict function .

Please let us know if there is any difficulty. Thank You.

**Comment by 3048205169** [comment]
Oh, I have missed the file that I have to upload!

**Comment by 3048205169** [comment]
> caMicroscope uses tensorflow.js models for classification and segmentation . Some example models can be found here .
> The input patch size is the size of patches on which the model was trained .
> For example , for this model the input patch size should be 512 , the classes should be benign, normal, insitu and invasive and the format should be RGB .
> The normal workflow for uploading a model is something like :
> 
> fill in the details as mentioned above.
> Upload the tfjs model: The first upload is for the model.json file and the next one is for all the binaries. For the example above all files are present here .
> Once uploaded this is a guide that can help for using the Predict function .
> 
> Please let us know if there is any difficulty. Thank You.

![models](https://user-images.githubusercontent.com/38618523/85245030-f522df80-b478-11ea-9ea1-2baaba36ebf0.png)

**Comment by birm** [comment]
Thanks @leoarc for helping to handle this! @3048205169 has this answered your questions?

**Comment by 3048205169** [comment]
> Thanks @leoarc for helping to handle this! @3048205169 has this answered your questions?

Yes! Althought I am not sure about the inner mechanism of the model, but I guess the calling of the classification is in the model.js.

I am not good at js, maybe I have to learn it.

**Comment by birm** [comment]
I'm afraid I don't quite understand. Are you asking about the model structure, or are you asking about the prediction application? (Or both?)

**Comment by 3048205169** [comment]
There are runPredict function in the model.js file which will call the model uploaded but I am not very good at .js file.

**Comment by birm** [comment]
I've added #413 to hopefully eventually help readability.

However, for now, I think you're looking for [this line](https://github.com/camicroscope/caMicroscope/blob/master/apps/model/model.js#L568 ) and the tf.tidy block it's in. Or maybe you're interested in [model storage](https://github.com/camicroscope/caMicroscope/blob/07a0f994aa3252b42c51a800b4e9fe468a45ff2d/apps/model/model.js#L487), which is done in browser.

**Comment by birm** [comment]
Closing as a stale issue. Feel free to reopen if you think this should be active still.
