### ISSUE TITLE
Improved In-Code Documentation

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#413]
Some things are pretty difficult to read, and could likely use a bit of help.
Thus, describe at a high/medium level (as appropriate) as code comments.
Use judgement to determine if something is already clear.
(that is the following is probably not necessary)
```js
// performs normalization on an image
normalizeImage(img)
```
We'll probably break this into subtasks, depending on what PRs come in.

**Comment by Saurav-Majumder** [comment]
Can I help through it

**Comment by anumi1999** [comment]
Is this issue still open?

**Comment by birm** [comment]
Yes, thanks for your interest. I'd recommend doing some small sections first so we can review before you put too much time into it.

**Comment by anumi1999** [comment]
Made some changes in the documentation please have a look and review

**Comment by AkhileshAdithya** [comment]
Is this issue still open? Are contributions welcome?

**Comment by garvpatidar04** [comment]
is this still open? Can I contribute to it?

**Comment by ashutosh887** [comment]
I would like to work on this Issue. @birm

**Comment by AdarshRawat1** [comment]
May I inquire whether this opportunity is presently available for contribution? If so, I would appreciate the chance to make a contribution.

**Comment by birm** [comment]
We welcome pull requests on open issues from anyone!

**Comment by Znoy108x** [comment]
I would like to contribute in this !

**Comment by NikhilKnox** [comment]
is this open? Can i contribute!

**Comment by Sankalp-sa** [comment]
I would like to contribute int this

**Comment by Sam-1806** [comment]
Is this open? Can I contribute?

**Comment by Shubhisingh921** [comment]
I would like to contribute in this as i am good at documentation.

**Comment by AmanGuptaCoder** [comment]
I would like to contribute in documentation.

**Comment by affusul** [comment]
i would like to contribute to this,if it is open.

**Comment by birm** [comment]
I'm going to close this issue, not because it is done, but because it can never really be "finished". 
I will still accept pull requests which meaningfully improve documentation.

**Comment by niikkhilsharma** [comment]
Hey, Birm
I understand your concern but I would like to give it a try. I am good at managing and writing documentation. I have written couple of documentation for several projects and I believe that I can help at this. I hope you will give me a chance. 
Thanking You
