### ISSUE TITLE
The structure graph and description of the entire programme

### ISSUE THREAD

**Issue by 3048205169** [camicroscope/caMicroscope#416]
I used to be a CS undergraduate student thus I was used to drawing software structure graph. Therefore, even if someone is not familiar with some of the parts of the software, he can easily figure out their functions.

I am not sure about the structure of the caMicroscope, the entire software. I can easily understand some of the functions of some of the parts of the program but not all. For example, the JS model which I am now trying to understand is somehow difficult for me.

Now I would like to make some contributions to this program, but after the modification to the toolbar, many bugs appears because of the changes I made. I am even not sure about the result after I made a change.

I wonder if there exists such a structure graph or description.

Thanks!

**Comment by birm** [comment]
I missed this issue report until now.
Do you mind providing an example for the kinds of diagrams you are looking for?

**Comment by 3048205169** [comment]
> I missed this issue report until now.
> Do you mind providing an example for the kinds of diagrams you are looking for?

I mean if there is something like the developing document which I could read.

I would like to add some new functions to the CAMICROSCOPE but it is not realistic for me to do a research on the entire project, so I wonder if there is developing document to read.

**Comment by birm** [comment]
We do have https://github.com/camicroscope/caMicroscope/blob/master/CONTRIBUTING.md but I'm still not sure what you're looking for. Do you have an example from another project?

**Comment by SAP-20** [comment]
A newbie in open source.Can i work in this issue??

**Comment by birm** [comment]
I'll accept pull requests, but I'm not perfectly sure what's desired for this issue. I'd say if you make something which _you_ find useful, that's a good start. :)

**Comment by birm** [comment]
Closing as a stale issue. Feel free to reopen if you think this should be active still.
