### ISSUE TITLE
Sign-up Page Masking Bug

### ISSUE THREAD

**Issue by VincentVTran** [camicroscope/caMicroscope#422]
**Describe the bug**
When entering the sign-up page, the password masking is given the value "['list','of',filters']" instead of password

**To Reproduce**
1. Go to https://wolf.cci.emory.edu//camic_org/apps/signup/signup.html

**Expected behavior**
The second input should state password instead of an array of strings

**Screenshots**
![image](https://user-images.githubusercontent.com/41248060/87235365-fcb31580-c3a0-11ea-86e6-44e20e45d6fc.png)

**Desktop (please complete the following information):**
 - Window 10
- Chrome

**Comment by birm** [comment]
Signup is not done with a password; it's done through a third party provider, usually google (though any jwk url may be selected).

**Comment by birm** [comment]
I think that this is a common misconception; do you have any recommendation on how to clarify this for other users in the future?

**Comment by VincentVTran** [comment]
> Signup is not done with a password; it's done through a third party provider, usually google (though any jwk url may be selected).
Ah, so what exactly is typed below the email then?

**Comment by birm** [comment]
We're mid-development in the ability to mask certain items from certain users. That is, some users may only see items tagged with "A" in a field we've labeled "filter". That's what this field is for. Admittedly, a single text field is not a good way to display this.
