### ISSUE TITLE
Already have an account tag

### ISSUE THREAD

**Issue by VincentVTran** [camicroscope/caMicroscope#423]
**Is your feature request related to a problem? Please describe.**
On the sign-up page, the "already have an account" text does not redirect to a login page.

**Describe the solution you'd like**
I would like to fix that by revising the html page for the sign up

**Describe alternatives you've considered**
Add an address element in place of that div tag.

**Comment by narendraiiitl** [comment]
I would like to work on this issue.

**Comment by birm** [comment]
solved with #461
