### ISSUE TITLE
Drawing Failed to work

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#449]
Click the pencil, and it does not draw

Uncaught TypeError: Cannot read property 'style' of undefined
    at MouseEvent.annotationOn (uicallbacks.js:338)
    at MouseEvent.<anonymous> (uicallbacks.js:290)

**Comment by nanli-emory** [comment]
Fixed:
1. set a default value for `operationpanel.js`.
2. fixed the `openseadragon-canvas-draw-overlay.js`

**Comment by birm** [comment]
confirmed. thanks Nan!
