### ISSUE TITLE
Error  using a model over the selected region

### ISSUE THREAD

**Issue by Brayan-Valenzuela** [camicroscope/caMicroscope#453]
Download the caMicroscope, Distro and Caracal repositories, follow the suggested settings in the caMicroscope repo in the "Fast Local Changes" section. I loaded a test classification model and when I tried to run the model on a region of interest it did not work and the console had a TypeError error (see image) but applying the model on the whole image works perfectly. Someone has had a similar error or can you help me with this problem?

![image](https://user-images.githubusercontent.com/44003588/99491329-8ec3bf80-2939-11eb-8f88-2bf89bb5fe05.png)

 - ubuntu 20
 - opera and google chrome

**Comment by birm** [comment]
I was easily able to replicate this. Thanks for the report! Debugging now.

**Comment by Brayan-Valenzuela** [comment]
I was able to fix the problem, I think there is a bug in the repository code that is important to fix soon. The undefined that I show in the photo, is because the object "imgColl" that enters the function "checkSize" of the file "model.js" is asked for parameters that it doesn't have, like for example: "imgColl.features[0]. bound[0]" reviewing the object structure I found that the correct parameter request is: "imgColl.features[0].bound.coordinates[0][0]" when I made a couple of changes taking into account this structure, the viewer works correctly and I solved my problem. I verified this by checking the code of the demo https://wolf.cci.emory.edu//camic_org/apps/viewer/viewer.html?slideId=5bec456369056d7e537c2a9b

 and comparing it with the code of my viewer in the local host (attached photo)

I was able to fix the problem, I think there is a bug in the repository code that is important to fix soon. The undefined that I show in the photo, is because the object "imgColl" that enters the function "checkSize" of the file "model.js" is asked for parameters that it doesn't have, like for example: "imgColl.features[0]. bound[0]" reviewing the object structure I found that the correct parameter request is: "imgColl.features[0].bound.coordinates[0][0]" when I made a couple of changes taking into account this structure, the viewer works correctly and I solved my problem. I verified this by checking the code of the demo https://wolf.cci.emory.edu//camic_org/apps/viewer/viewer.html?slideId=5bec456369056d7e537c2a9b

 and comparing it with the code of my viewer in the local host (attached photo)

![image](https://user-images.githubusercontent.com/44003588/99547842-03bce680-2986-11eb-8a2a-380a3b13c48f.png)
![image](https://user-images.githubusercontent.com/44003588/99547890-10413f00-2986-11eb-9a1f-e29d24498178.png)

**Comment by Brayan-Valenzuela** [comment]
I already have a fixed version, in case it helps you.

**Comment by birm** [comment]
@Brayan-Valenzuela Looks like you maybe beat me to it. That said, if you think your fix is better than #454 (or otherwise are looking to contribute), We'd warmly welcome a pull request!

**Comment by Brayan-Valenzuela** [comment]
The bug is already fixed, than you for your time.

**Comment by birm** [comment]
Thank you for your time, and taking the time to make a detailed report!

**Comment by Brayan-Valenzuela** [comment]
Hi Brim, I've been testing the fix that the repository did in the develop branch, on the issues #453 that I previously reported. Following the same steps that I described in issue #453 I realized there is a visual bug with the segmentation that is done on the image, the segmented region is deformed once the marking is done, and the model runs normally.

**Comment by birm** [comment]
That's Interesting if concerning. Do you want to attempt a fix, or would you like me to look at it?

**Comment by Brayan-Valenzuela** [comment]
With the little that I have reviewed the code of the model.js file and comparing it with the one I found in the demo of the caMicroscope page, I made a fix that apparently works, I could share it with you to evaluate it.

**Comment by Brayan-Valenzuela** [comment]
![image](https://user-images.githubusercontent.com/44003588/99805098-fe88a480-2b09-11eb-84c7-46f552f2fdb3.png)
![image](https://user-images.githubusercontent.com/44003588/99805126-08aaa300-2b0a-11eb-8bfd-e94588ecc8b9.png)
I oly change this 3 lines in the file "model.js" and apparently it works

**Comment by birm** [comment]
That looks about right to me! Would you like to open a pull request with these changes? :)

**Comment by Brayan-Valenzuela** [comment]
Yes sure, what I need to do?

**Comment by birm** [comment]
If you haven't made a fork yet, the easiest thing is to go to the file in github, and click the pencil and make your changes. That will open a pull request automatically.

**Comment by Brayan-Valenzuela** [comment]
Already request changes on segment.js and model.js files. A new branch called patch-1 was created in my user
