### ISSUE TITLE
Upload ".jpg" images for visualization

### ISSUE THREAD

**Issue by Brayan-Valenzuela** [camicroscope/caMicroscope#458]
The data set I have contains .jpeg images, however when I upload them to the viewer, it says that this format is not compatible. 

As a solution, I thought of converting the .jpeg images to .tiff, since this format does accept it. However, you can see in the image the error that comes out when you try to upload it. 

![WhatsApp Image 2020-11-30 at 10 38 09 AM](https://user-images.githubusercontent.com/44003588/100630139-2ccf6680-32f8-11eb-8dbd-e81863591239.jpeg)

**Comment by birm** [comment]
Thanks for the report.
It's unfortunately not enough for it to be just a tiff, it needs to be a pyramidal tiff. We've added [a route](https://github.com/camicroscope/SlideLoader/blob/62b4b0fba92c601e8ed95f52c49cd17020ff05fb/SlideServer.py#L65) that I don't think we use yet for this kind of conversion. Alternatively, [this link](https://libvips.github.io/libvips/API/current/Making-image-pyramids.md.html) may be useful. Please let me know whether or not this works for you.

**Comment by Brayan-Valenzuela** [comment]
The solution was a perfect fit for our use case, thank you very much.
