### ISSUE TITLE
Minor UI issues in slides page.

### ISSUE THREAD

**Issue by narendraiiitl** [camicroscope/caMicroscope#462]
**Describe the bug**
1. The footer appears at the mid-screen on the slide page.
2. Info page also highlights the slides button.

**To Reproduce (1) **
1. Go to 'Table page'
2. see it

**To Reproduce (2) **
1. Go to  'Info page'
2. see it

**Expected behavior**
1. The footer should appear at the bottom of the page.
2. Only one tab should be active.

**Screenshots**
If applicable, add screenshots to help explain your [problem.]
![Screenshot (30)](https://user-images.githubusercontent.com/54548515/101668797-04bdd100-3a77-11eb-8dea-b298b16e26b1.png)
![Screenshot (32)](https://user-images.githubusercontent.com/54548515/101668809-07202b00-3a77-11eb-863e-f06f79f0c06d.png)

**Desktop (please complete the following information):**
 - Windows
 - chrome

**Comment by akhil-rana** [comment]
I think we removed the "info" option from the navbar at some point in the past.
Since the toggle already exists in slides page I'm not sure if info should be present in the navbar.
@birm what do you think?

**Comment by birm** [comment]
I think you're right; it should be one place or the other, not both. :)

**Comment by birm** [comment]
@narendraiiitl are you interested in fixing this yourself?

**Comment by narendraiiitl** [comment]
Sure. thanks for considering me.

**Comment by birm** [comment]
closed by #464 :smiley:
