### ISSUE TITLE
Formalized Way to add Link Buttons 

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#468]
Very frequently, I'm asked to add links to forms to deployments. While this isn't difficult, it seems to be a well-used enough feature to add a formal way here and in camicroscope/Distro to add these link buttons. (e.g. a list of the button icon name and url?)

**Comment by Ritikyadav007** [comment]
Sir i would like to work on this can you explain the issue in detail( where to add link buttons).

**Comment by birm** [comment]
In the toolbar! You could use the bug report button as an example.

**Comment by nafees87n** [comment]
Do you need a function in /Distro that could add buttons to the toolbar, or a button in the toolbar which would add buttons to the toolbar?

**Comment by birm** [comment]
The first one. I imagine it would be a config js file which would be mounted in static to allow for custom buttons.

**Comment by birm** [comment]
If you're using a json, you may need to fetch it from a url. The benefit of using a js file instead may be that you wouldn't have mess with fetch, but the downside would be that a json would be more standard. Either way is certainly acceptable as far as I'm concerned :)

**Comment by birm** [comment]
I should clarify that this is for the toolbar in the viewer!

**Comment by Vedant1202** [comment]
@birm This issue could be closed ? Or is there more to it?
