### ISSUE TITLE
Running `npm run lint` shows ERROR on Windows

### ISSUE THREAD

**Issue by sohamsshah** [camicroscope/caMicroscope#469]
**Describe the bug**
Running `npm run lint` gives errors.

**To Reproduce**
1. `git clone https://github.com/username/caMicroscope.git`
2. `cd caMicroscope.git`
3. `npm install`
4. `npm run lint`

**Expected behavior**
There should not be any linting errors.

**Screenshots**
![ss](https://user-images.githubusercontent.com/47717492/103857003-a74f8b00-50db-11eb-9688-7ea278e778ed.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

On running `npm run lint-fix` solves this problem.

I am unsure that if this is relating to OS or the repository. Would love to work on this. Thank you.

**Comment by birm** [comment]
I think you should be able to add `"linebreak-style": 0` to the lint rules to avoid this.

**Comment by sohamsshah** [comment]
Thank you for the help. 

P.S. This is my first contribution to caMicroscope 😊
