### ISSUE TITLE
User Guide Screencast link doesn't open correctly on Google Drive

### ISSUE THREAD

**Issue by sohamsshah** [camicroscope/caMicroscope#471]
**Describe the bug**
The User Guide Screencast link when opened  on Google Drive doesn't open correctly.

**To Reproduce**
1. Go to [README.md](https://github.com/camicroscope/caMicroscope/blob/master/README.md)
2. Scroll to `nanoborb` section
3. Click on the [user guide screencast](https://drive.google.com/file/d/1HkkL5FqEIgi7fzqKijtUhWBPlplh_uHF/view)
4. See the opened link.

**Expected behavior**
It should serve the purpose of the user guide and play the video or similar.

**Screenshots**
The snapshot of that can be seen as under:

![screencast](https://user-images.githubusercontent.com/47717492/103977738-e0513380-519f-11eb-8ad8-353b1e80b963.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
It shows that the content has been moved to trash. Maybe we can restore it or if its outdated, then we can create a new video/guide screencast too. I would love to help in any way possible. Thank you.

**Comment by birm** [comment]
Ah, sorry about that. does it work now?

**Comment by sohamsshah** [comment]
Yes, it works 😁 Btw I have posted some views in #267 and also started a small disussion in Google Group channel. Would you like to have a look at it? Thank you!

**Comment by sohamsshah** [comment]
Closing this 🙌
