### ISSUE TITLE
nanoBorb not working on macOS 10.15.7

### ISSUE THREAD

**Issue by hongjuny** [camicroscope/caMicroscope#474]
nanoBorb for macOS available on the repo is not working on my iMac with macOS 10.15.7. I don't know but I haven't seen an instruction on how to compile from source. Would you please give me guidance? Thank you!

**Comment by birm** [comment]
we haven't built a release in a while -- https://github.com/SBU-BMI/Nanoborb/releases/tag/1.5.0

That said, @ebremer has been the person making nanoborb releases.
