### ISSUE TITLE
Async Hierarchical Layer Manager Organization

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#484]
Make Layer Manager Async-focused.
(from u24)
User has recommended only showing _types_ of layers for a slide, and only breaking down on request. This would give us time to run a non-blocking async call to populate detailed lists, especially given that segmentation calls take up to 7 seconds. 
this also has the UX benefit of matching user's model of describing items by type first, rather than by provenance.

**Comment by nanli-emory** [comment]
Finished loading the layers info asynchronously. (Commit: 9fe44b1e)

I'm going to work on optimized massive loading annotations when you click all show all annotations

**Comment by nanli-emory** [comment]
@birm Should we close this issue?
