### ISSUE TITLE
[BUG]: Trouble uploading new file 

### ISSUE THREAD

**Issue by sohamsshah** [camicroscope/caMicroscope#489]
**Describe the bug**
When trying upload a new file through `table.html`, it throws error with status code - 500. 

**To Reproduce**
1. Go to [table.html](http://localhost:4010/apps/table.html)
2. Click on `Upload`
3. Select `Browse` and choose a file to upload. (Preferably choose any of the test files from [here](https://github.com/camicroscope/Distro/tree/master/images) )
4. It will take a bit to load.
5. See error with status code: 500
6. **IMP**: After unsuccessful attempt to upload the file, click `close`. 

*Not sure if the below issue is related with the upload bug. If not related, can resolve it in another discussion/issue*
7. Again click on `upload`.
8. See the Arrow button, which is not supposed to be there when uploading a new file as it doesn't make sense.
9. Reload the page and see the button vanish.

**Expected behavior**
It should upload the slide with proper acknowledgement.
**Screenshots**
![statusCode_bug](https://user-images.githubusercontent.com/47717492/107761077-c8e20900-6d50-11eb-8513-481b423d6ce2.PNG)
![statusCode_bug_2](https://user-images.githubusercontent.com/47717492/107761081-caabcc80-6d50-11eb-8863-62962d64cc63.PNG)

**DEMO VIDEO**

https://user-images.githubusercontent.com/47717492/107764817-d8645080-6d56-11eb-8d91-3ae5ca63eb9e.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 88 (latest)

**Smartphone (please complete the following information):**
 - Device: Moto Z Play
 - OS: Android
 - Browser: Chrome
 - Version: 87

**Additional context**
I am not sure why I am facing the error. Is there some issue with my local configuration or some other problem?

Would like to work on this. Can you provide some context/insights why this might be happening?

**Comment by birm** [comment]
Are you seeing any crash or anything interesting with the ca-back or ca-load services in the docker logs?

**Comment by sohamsshah** [comment]
![image](https://user-images.githubusercontent.com/47717492/107822060-7ed64300-6da3-11eb-83c1-ed2bb54ce45e.png)

Getting this log.

**Comment by sohamsshah** [comment]
This was solved by reinstalling docker containers and redoing the dev env setup. Closing this issue, thanks!
