### ISSUE TITLE
Linting error re: variable/class naming

### ISSUE THREAD

**Issue by sohamsshah** [camicroscope/caMicroscope#492]
**Describe the bug**
Lint error found in the `layersviewer.js` codebase. 

**To Reproduce**
1. Open CLI at path .../camicroscope/caMicroscope
2. RUN `npm run lint-fix` or `npm run lint`
3. See error

**Expected behavior**
No linting errors expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/47717492/107903406-2ce21880-6f6f-11eb-8ba1-1bf9af9420a6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This is probably a quick-fix and a good first issue for new contributors.

[This](https://eslint.org/docs/rules/camelcase) might helpful :)

**Comment by kahanikaar** [comment]
I would like to work on this issue. @sohamsshah

**Comment by birm** [comment]
I suspect that this happened because another build was failing, so @nanli-emory 's changes weren't sanity checked by the lint build.
Should be a pretty straightforward fix :) Just make sure you don't break anything.

**Comment by nanli-emory** [comment]
I will update the latest code and also will fix eslint error. ;)

**Comment by nanli-emory** [comment]
fixed ~~~ thanks
