### ISSUE TITLE
Annotations Not loading

### ISSUE THREAD

**Issue by Hemansh31** [camicroscope/caMicroscope#495]
**Describe the bug**
Annotations are not being loaded even after being saved. 

**To Reproduce**
1. Open any slide
2. Add and save an annotation
3. Go back to home
4. Open the same slide again. Try to load the annotation. You will see the error.

**Expected behavior**
Annotations should get loaded
 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Browser [e.g. chrome]]

**Additional context**
This problem may be due to the latest commit in the develop branch as my local repo which was one commit behind was working fine until I pulled the changes.

**Comment by birm** [comment]
For clarity, do you mean commit https://github.com/camicroscope/caMicroscope/commit/9db74bee06b0993af549ae8a28c94718a18175d2?

**Comment by Hemansh31** [comment]
Yes

> For clarity, do you mean commit [9db74be](https://github.com/camicroscope/caMicroscope/commit/9db74bee06b0993af549ae8a28c94718a18175d2)?

**Comment by nanli-emory** [comment]
@Hemansh31 Could you open your devTools on Chrome and check any errors there?

**Comment by birm** [comment]
If it's no trouble, can you tell us what the resolution to this was? If there's something less intuitive about the UI, maybe we could telegraph it better.

**Comment by Hemansh31** [comment]
Actually this was my foolishness, I did not pull the changes in the Distro and Caracal Repo :),
