### ISSUE TITLE
Footer and About Page

### ISSUE THREAD

**Issue by Priyaraj17** [camicroscope/caMicroscope#516]
**Is your feature request related to a problem? Please describe.**
A footer and an about page should be present. 

**Describe the solution you'd like**
Hey, I was thinking of including an about page which tells the users about caMicroscope. I was also thinking of including a footer which will contain links to various pages and social networking sites.

**Describe alternatives you've considered**
I am hoping to get some opinions related to it. Thank you

**Comment by PRASANNA-416** [comment]
Yeah ,That will be great and useful for the newcomers . Myself , I joined a week ago in the slack channel and it would help me get started and know more about the organization !!

**Comment by Priyaraj17** [comment]
@PRASANNA-416 Hey, You can talk to the mentors related to this. Thanks!

**Comment by somnathPrasad** [comment]
Hey, is this issue open I would like to contribute.

**Comment by abhijeet-26** [comment]
Hey @Priyaraj17 , is this issue open? I would love to contribute.

**Comment by ShivamKaushik316** [comment]
if the issue is still open , i would like to contribute as well

**Comment by srvjha** [comment]
Can i contribute to this issue?

**Comment by rishuraj1** [comment]
I would really like to contribute to this issue, is it still open?

**Comment by lalitkumawat1m** [comment]
Can i work on this issue ?

**Comment by goodylove** [comment]
@birm hello i am goodness an Outreachy intern  i would love to work on this issue

**Comment by SakshiVar** [comment]
@birm Is it still open? I would like to contribute to this issue.

**Comment by birm** [comment]
I think this is resolved with the camicroscope.org site
