### ISSUE TITLE
Bootstrap version update

### ISSUE THREAD

**Issue by Priyaraj17** [camicroscope/caMicroscope#517]
**Is your feature request related to a problem? Please describe.**
Upgrade bootstrap version from 4.4.1 to 5.0.0

**To Do**

- [ ] Are all the bootstrap component working?
- [ ] User Interface should be correct.

**Comment by Priyaraj17** [comment]
@akhil-rana  @birm May I work on this issue? I would have to test that the latest bootstrap version doesn't create any issues on all the pages.

**Comment by birm** [comment]
Table.html, at least, still uses bootstrap 4

**Comment by Priyaraj17** [comment]
I am closing this issue now, I hope things were resolved...
