### ISSUE TITLE
Annotations addition is not behaving as expected

### ISSUE THREAD

**Issue by Hemansh31** [camicroscope/caMicroscope#541]
**Describe the bug**
After adding annotations and clicking on the save button the slide freezes unable to zoom or pan or use any other feature. Also, after clicking reset while adding annotations annotations are not getting drawn. In state 1 of the annotations addition this error is faced.

**To Reproduce**
1. Draw any annotation
2. Click on Save button in the Layers Manager
3. Try to zoom and pan the slide
5. Draw any annotation
6. Click on Reset button in the Layers Manager
7. Try drawing annotation again
8. See error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome

**Comment by r7rohan** [comment]
I think this is because of my changes, just going to push most recent ones. Also, the behaviour of state-1 has been changed (it won't be automatically saved) so that user can use moving point/ Smartpen features.
