### ISSUE TITLE
nanoBorb Documentation Missing  

### ISSUE THREAD

**Issue by thesloppyguy** [camicroscope/caMicroscope#546]
**Is your feature request related to a problem? Please describe.**
In the README documentation there is a mention of nanoBorb, as a standalone application for individual users without a server. It has a linked attached to it for a section called "#nanoborb". As the section doesn't exist in the Document, so no redirects occur for the user. Leading to a dead end.

**Describe the solution you'd like**
If the documentation already exists, we should modify the link so it points to the correct documentation.
Otherwise if documentation doesn't exist, we should create one ASAP and mention the progress in the READ ME.  

**Describe alternatives you've considered**
If the documentation and the feature both don't exist, we should remove this portion "nanoBorb covers nanoBorb, the version of caMicroscope designed as a standalone application for individual users without a server." from README  to avoid user confusion in the future. 

**PS**
I would be happy to work on this issue. Guidance along the way would be appreciated.

Ref: https://github.com/camicroscope/caMicroscope/blob/master/README.md

**Comment by manikmmalhotra** [comment]
@birm can i start with this issue if no-one working on this?

**Comment by birm** [comment]
I'll always welcome PRs :)

**Comment by chezhia** [comment]
Any updates on this issue? We are also interested in using this in standalone mode within our development container.

**Comment by birm** [comment]
Hi @chezhia! We haven't rebuilt nanoborb in a while, but you can find it at https://github.com/sbu-bmi/nanoborb
