### ISSUE TITLE
redirecting to home screen while login-in with google

### ISSUE THREAD

**Issue by manikmmalhotra** [camicroscope/caMicroscope#554]
**Describe the bug**
when user login using google-authentication in slides tab or info tab it get redirect to the home-screen, user should be on the same screen.

**To Reproduce**
1. Go to 'Slides or Info'
2. Click on Sign In with google'
4. See error it redirect to home

**Expected behavior**
it should redirect to info screen or slides screen

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10
 Brave

**Additional context**
I would be happy to work on this issue.

**Comment by birm** [comment]
I bet I just messed up something on the login code. If you want to contribute, changes should be applied here - https://github.com/camicroscope/Distro/blob/master/config/login.html

**Comment by SourasishRoy1501** [comment]
Is this issue resolved?

**Comment by payaldutta** [comment]
If this issue is not resolved, I will want to work on it @birm 
Thank You.

**Comment by birm** [comment]
I do try to keep up with open pull requests, if anyone can replicate and fix!

**Comment by tanmay-raj-29** [comment]
Hey @birm is this issue still open? 
Thank you.

**Comment by priiyaanjaalii0611** [comment]
Hey! I am new to open source contribution. I found camicroscope project very intriguing, if this issue is still open can I try solving it? I really want to contribute and learn during the process

**Comment by birm** [comment]
Thanks everyone for your interest in, reporting of, and patching for this!
