### ISSUE TITLE
errno -3008 ENOTFOUND 

### ISSUE THREAD

**Issue by IPorth** [camicroscope/caMicroscope#561]
Error while uploading a wsi.

**To Reproduce**
1. Accessed camicroscope via http://localhost:4010/apps/landing/landing.html
2. Click on Slides, then on upload
3. Selected a file (.svs) stored on the server I'm working on 
4. Upload is running
5. Entered slidename and clicked on the arrow
6. Error message apears

**Screenshots**
<img width="959" alt="error" src="https://user-images.githubusercontent.com/66480354/180217112-31ffd2ca-6af6-48f1-8868-362495d0650e.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Browser: Chrome (Version 93.0.4577.82 )

**Comment by birm** [comment]
On your host, can you see anything for `docker logs ca-load`?
