### ISSUE TITLE
Is it possible to use caMicroscope with an iipimage-server installed separately? 

### ISSUE THREAD

**Issue by catweis** [camicroscope/caMicroscope#574]
**Describe the solution you'd like**
I have an organized set of folders with WSI and adjacent other files. To view and annotate, I want to use caMicroscope.
Is it possible to install (for example) on one Linux machine an iipimage-sever to present the images and view it with a caMicroscope installation on another machine?
I want to avoid uploading or copying my image files.

**Comment by birm** [comment]
The field IIP_PATH for our backend controls how the proxy is set up for iip. (see https://github.com/camicroscope/Distro/blob/4f107ac106b8ebd0422de32b6e9d69d00d0f517d/caMicroscope.yml#L37). Also it's important to note that the IIP version we use is configured with openslide, and vanilla iip probably won't work on your slides.

I'd like to point out that this would mean that our ordinary slide metadata extraction "loading" process would not work, but this could be resolved by manually adding the metadata into the mongo database.

Please let me know if you want help with any of this; perhaps we could add some config/helpers for this kind of architecture.

**Comment by catweis** [comment]
Thank you very much for your fast response.
Then I am trying to install your “iip-version” on one server and the rest (with modified docker compose) on the other machine.
For me is crucial that there is no copying or loading of the WIS required. Would that also be not the case with an installation on one system?
May I ask what the metadata does comprise?

**Comment by birm** [comment]
See https://github.com/camicroscope/Distro/blob/4f107ac106b8ebd0422de32b6e9d69d00d0f517d/config/test_seed.js#L3 for a reasonably minimal version of what's required. Mpp is "microns per pixel" and is needed for any tool which uses physical measurements.

**Comment by tomararun** [comment]
Is this still open? Can I contribute to it.

**Comment by birm** [comment]
Hi @catweis , I'm marking this as stale/resolved, but feel free to comment/reopen if this needs more discussion or help. Thank you!

**Comment by tomararun** [comment]
Thank you for notifying me. I acknowledge that issue #574 has been closed
as completed.
