### ISSUE TITLE
503 Service Unavailable in Landing page.

### ISSUE THREAD

**Issue by inceptionabhishek** [camicroscope/caMicroscope#575]
**Describe the bug**
503 Service Unavailable on landing.html page. After clicking on the demo button from the home page, we get to see the landing page, but sadly its services are unavailable as of now.

**To Reproduce**
1. Go to `https://camicroscope.github.io/`
2. Click On the view Demo button.
3. View error

**Expected behavior**
A demo of the application should be visible but as of now due to some server error its showing a 503 error.

**Screenshots**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/65409282/221339865-3420b4d2-dd4f-4003-8f75-dfd562289d41.png">

**Comment by utkarsh006** [comment]
Can I work upon this issue?

**Comment by inceptionabhishek** [comment]
@utkarsh006,
brim aka @birm self-assigned this issue, so You can check out other issues.
