### ISSUE TITLE
Inconsistent navbar on workbench section

### ISSUE THREAD

**Issue by JayashTripathy** [camicroscope/caMicroscope#577]
**Describe the bug**
the contents inside of navbar is not adapting with different screen sizes in workbench section

**To Reproduce**
1. Start the development environment
2. Go to 'http://localhost:4010/apps/landing/landing.html'
3. Click on 'hamburger menu'
4. Select 'Workbench'
5. See the bug

**Expected behavior**
workbench text should adapt its position according to screen size
 

![Screenshot 2023-02-28 211120](https://user-images.githubusercontent.com/76092296/221904427-09629534-5fef-4056-80a7-01a1ff47b59c.png)

**Current behavior**
![Screenshot 2023-02-28 211120](https://user-images.githubusercontent.com/76092296/221903645-f2e5ffc4-7814-4fdd-b092-a11cbaf19ae3.png)

 - Browser [e.g. chrome, firefox]

Can I work on this issue ?

**Comment by Naseem010** [comment]
can be resolved using media query or can be solved by detect the screen size using the window.innerWidth property.Check if the screen size is less than or equal to the width of your navbar.If the screen size is less than or equal to the navbar width, add a class to your navbar that will change its position from static to fixed using the position CSS property. You can also add other styles to adjust the position and size of the navbar.When the screen size is larger than the navbar width, remove the class from the navbar to restore its original position.

Sampled code:-

// Get the navbar element
const navbar = document.querySelector('.navbar');

// Set the navbar width
const navbarWidth = 768; // adjust this value as needed

// Function to handle screen size changes
function handleResize() {
  // Get the screen width
  const screenWidth = window.innerWidth;

  // Check if the screen is small enough to modify the navbar
  if (screenWidth <= navbarWidth) {
    // Add the "fixed" class to the navbar
    navbar.classList.add('fixed');
  } else {
    // Remove the "fixed" class from the navbar
    navbar.classList.remove('fixed');
  }
}

// Add a listener for screen size changes
window.addEventListener('resize', handleResize);

// Call the function on page load
handleResize();

**Comment by Naseem010** [comment]
Should i work on this issue?

**Comment by prashulkale** [comment]
Is this issue still open ? If yes, i would love to work on it.

**Comment by ShivamKaushik316** [comment]
Can i be assigned for the issue as i have fixed it already ?

**Comment by ShivamKaushik316** [comment]
#580

**Comment by Purnima3** [comment]
can I work on this issue?

**Comment by abhijain2003** [comment]
I have already worked on it, waiting for maintainers to raise pull request
