### ISSUE TITLE
The Reload button is not Responsive for small size devices

### ISSUE THREAD

**Issue by Techkrish1** [camicroscope/caMicroscope#578]
**Describe the bug**
On the slide page, The reload button is not responsive. The button's right edges are cut into small devices. It also makes less Ui.

**To Reproduce**
1. Go to 'Slide page'
2. Make the device screen under400px
3. See the reload button's right edges are cut.

**Screenshots**

Before Fixxing

![image](https://user-images.githubusercontent.com/111285228/222021234-4ddfe229-ead2-498a-ad01-23802987aef2.png)

After Fixxing

![image](https://user-images.githubusercontent.com/111285228/222021570-03672732-eb27-4589-b4cc-ff6e2d8805e9.png)

**Comment by Arpitkandwal** [comment]
Is this issue opened? Can i contribute to this?

**Comment by Arpitkandwal** [comment]
@Techkrish1 can you help me with running project on my device? you can share your email or something so i can contact you

**Comment by ShivamKaushik316** [comment]
if the issue is still open , i would like to contribute to this

**Comment by Techkrish1** [comment]
I fixed this issue. So, You can check out other issues.
