### ISSUE TITLE
Improve the UI/UX design of Website

### ISSUE THREAD

**Issue by TundeAdekoya** [camicroscope/caMicroscope#582]
**Describe the bug**
1) Navbar with unequal spacing for both margin and padding
2) Absence of semantic HTML tags for all contents on webpage. For instance, Using an H1 for the above the fold text **Perform Perfect Pathology with caMicroscope** instead of a div
3) Inadequate padding space to button for space around the call-to-action text
4) Small line height for paragraph text for users to consume content with ease
5) No use of buttons for the call-to-action in the join the community section
6) Footer is not consistent with design, and it is not responsive for all screens

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '[camicroscope.github.io](https://camicroscope.github.io/)'
2. See the following behaviours

**Expected behaviour**
1) Navbar should have equal spacing for both margin and padding
2) Use semantic HTML tags for all contents on webpage.
3) Proper padding space to button 
4) Legible line height for paragraph text
5) Use buttons for the call-to-action in the join the community section
6) Footer should be consistent with design, and it is responsive for all screens

**Screenshots**
![Navbar](https://user-images.githubusercontent.com/88208322/222731511-fa6c0fb3-f301-4218-8e82-473d5299eb15.png)
![Footer](https://user-images.githubusercontent.com/88208322/222731849-55fa8584-b663-4f38-aaf5-2ff49036951a.png)
![Screenshot (188)](https://user-images.githubusercontent.com/88208322/222732457-759057d4-4b1e-4691-b49e-ab2cc620d1c4.png)
![Line height](https://user-images.githubusercontent.com/88208322/222732523-291f7279-7c06-4506-873c-57eb65340871.png)

**Comment by ShivamKaushik316** [comment]
i would like to contribute in this issue

**Comment by Sankalp-sa** [comment]
I would love to improve this

**Comment by birm** [comment]
I'll review pull requests against https://github.com/camicroscope/camicroscope.github.io

**Comment by TundeAdekoya** [comment]
@birm Thanks, I'll also create this issue and a pull request on this repository [camicroscope.github.io](https://github.com/camicroscope/camicroscope.github.io)

**Comment by hrishi53** [comment]
i would love to help in this issue

**Comment by farmannaseem** [comment]
Hi 👋 I wanna work on this issue !!
Please assign me this !! 
Thank you !!🙂

**Comment by SharmaMuskan20** [comment]
Hello, Please assign me this issue. I would love to work on this.

**Comment by AbhishekCS3459** [comment]
@birm I want to contribute to it, please assign me this issue I am really really very much excited.

**Comment by srvjha** [comment]
Hey @brim I want to contribute to this issue , Can u please assign me ?

**Comment by ShubhamVSadigale** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by krcpr007** [comment]
Hey, can I improve the UI/UX of the website?
Please assign to me.

**Comment by sourav8927** [comment]
I would like  to work on this issue please assign to me,

**Comment by Sawmyaa** [comment]
I have designing knowledge with coding skills in HTML, CSS and JavaScript so I believe i can do it better @birm can you assign it to me?

**Comment by birm** [comment]
I'm closing this issue, but we still will review and possibly merge PRs against any actively-used components, including https://github.com/camicroscope/camicroscope.github.io
