### ISSUE TITLE
Navbar not displaying in documentation page

### ISSUE THREAD

**Issue by Arpitkandwal** [camicroscope/caMicroscope#583]
**Describe the bug**
Navbar is not displaying in caMicroscope documention page 

**To Reproduce**
1. Go to 'http://127.0.0.1:5500/apps/landing/landing.html'
2. 2. Click on more below documentation: 
![Screenshot (8)](https://user-images.githubusercontent.com/105699410/222955179-40e38724-9388-45be-bdf2-2847b4091b76.png)
3. You will get rendered to: 'https://camicroscope.github.io/docs/'

**Expected behavior**
Here you can see Navbar is not displaying.
**Screenshots**
![Screenshot (7)](https://user-images.githubusercontent.com/105699410/222955251-0485de8f-dc3c-44a1-9485-f0e3aa7614f5.png)

**Comment by Abhishekcpr** [comment]
Navbar code was not written in docs page.
Assign the issue to me I will fix that. 
![documentPage](https://user-images.githubusercontent.com/96368250/222968505-64af6e22-07c7-49bc-98d7-e33a1f00c573.png)

**Comment by abhijain2003** [comment]
I have already fixed it, waiting for maintainers to allow me to raise pr

**Comment by KousikRoy-EC** [comment]
Hey, can i work on this issue?

**Comment by AbhishekCS3459** [comment]
@Arpitkandwal  I want to claim this issue. Please assign it to me

**Comment by Arpitkandwal** [comment]
> @Arpitkandwal I want to claim this issue. Please assign it to me

Actually this issue is resolved by the mentor Ryan, he said there is no need of navbar there, so i'm closing this issue
