### ISSUE TITLE
Export Page UI/UX

### ISSUE THREAD

**Issue by kartikaysaxena** [camicroscope/caMicroscope#592]
Currently the UI/UX of export page is

<img width="1440" alt="Screenshot 2023-03-11 at 1 20 02 AM" src="https://user-images.githubusercontent.com/120778728/224415808-3c890011-4eef-49a7-99b0-84b5bd46a5f9.png">

After improvement it will look like this (responsive too)

<img width="1440" alt="Screenshot 2023-03-11 at 1 20 07 AM" src="https://user-images.githubusercontent.com/120778728/224416207-39eb56d0-8d24-477d-8bab-e1d40a53aff2.png">
nsive too)

I can make more improvements too.

**Comment by AdityaDey-80** [comment]
### **I WANT TO WORK ON THIS ISSUE**

UI can be updated in the following ways ---

- Start Consuming Inspirations.
- Always try to reflect your Inspirations through your designs.
- Know about basic constraints in UI.
- Take a look at new trends. 

Thanks & Regards ----

**ADITYA DEY**
