### ISSUE TITLE
UI / UX Improvements

### ISSUE THREAD

**Issue by B1TSH3LL** [camicroscope/caMicroscope#594]
The SignOut Button in Admin Panel has a bad hover effect.
![image](https://user-images.githubusercontent.com/85166079/224504986-662dd888-3695-457f-89b4-de339b50b46d.png)

i can try some magic!!! to fix this.

**Comment by AdityaDey-80** [comment]
### I WANT TO WORK ON THIS ISSUE 

UI can be updated in the following ways-

- Use white space.
- Optimize your page speed.
- Use attractive calls to action.
- Use hyperlink differentiation.
- Segment key information with bullet points.
- Use images (wisely).

Thanks and regards-

**ADITYA DEY**

**Comment by lalitkumawat1m** [comment]
I want to work on this issue please assign me;

**Comment by B1TSH3LL** [comment]
The PR Has been already been created for this issue. Please work on some other issue. Thanks For Showing Intrest.
