### ISSUE TITLE
Big Fat hamburger menu on home section & alignment issues in drop down menu

### ISSUE THREAD

**Issue by JayashTripathy** [camicroscope/caMicroscope#596]
**Describe the bug**
- A big fat hamburger menu is showing only on the home section (other section its perfect)
- the design(when we select it or hover it) of home button in drop-down menu is not acting normal

**To Reproduce**
1. Go to 'Dropdown menu(on small sreens)'
2. Click on 'Click on Home'
4. See Bug

**Expected behavior**
![Screenshot 2023-03-11 233905](https://user-images.githubusercontent.com/76092296/224508495-61f51d0f-a5f9-4b5c-b8a0-d6e97a352c89.png)

**Current behavior**
![Screenshot 2023-03-11 214317](https://user-images.githubusercontent.com/76092296/224508481-ca32f54b-9c9e-4a58-a151-f966f2c7b8ed.png)

**Desktop**
 - OS: [Android, iOS]

**Comment by JayashTripathy** [comment]
hey @birm  i have fixed this issue in #567, can you please review it.

**Comment by ssacharya2002** [comment]
Could you let me know if this issue has been resolved?

**Comment by birm** [comment]
Closed with #597
