### ISSUE TITLE
Not able to remove measurement

### ISSUE THREAD

**Issue by Sankalp-sa** [camicroscope/caMicroscope#598]
**Describe the bug**
When we try to measure after measuring 0.000 fm by mistake we cannot remove it.

**To Reproduce**
1. Go to 'measurements'
2. Make an measurement which is 0.000 fm
3. Then make a measurement.
4. Now try to remove that measurement it will give this error

**Screen Shot**
![image](https://user-images.githubusercontent.com/102241865/224536866-9b0b3050-5203-4137-a370-82952de32e1d.png)

**Video**
https://user-images.githubusercontent.com/102241865/224537419-21f2bf29-b610-46e1-928e-2680d0f3e9f8.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : chrome

**Comment by Sankalp-sa** [comment]
here the id of the measurement is undefined, so how to handle this I don't know. @birm could you help me a bit to solve this issue.

**Comment by B1TSH3LL** [comment]
i would like to work on this issue, please assign this to me. i can make this work possible, enchance too.

**Comment by rudrakshnalbalwar** [comment]
Please assign me this issue I can solve this.
