### ISSUE TITLE
Overlapping text in the workbench section

### ISSUE THREAD

**Issue by ShivanshAr97** [camicroscope/caMicroscope#599]
**Describe the bug**
There is overlapping of text in the workbench.html file when the user is viewing in the mobile layout.

**To Reproduce**
1. Go to 'Workbench' in the navbar in mobile layout
2. See error

**Expected behavior**
The text should not be overlapping and should appear something like this:

![image](https://user-images.githubusercontent.com/96040322/225312948-76c5e809-4c54-4c39-af2f-215d295271ab.png)

**Screenshots**

Currently it is looking like so:
![image](https://user-images.githubusercontent.com/96040322/225311916-6f8753d8-afc4-43bb-b418-9bef188cad25.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Brave

**Smartphone (please complete the following information):**
 - Device: Redmi
 - Browser: Chrome

**Comment by ShivanshAr97** [comment]
I would like to work on this issue please assign it to me

**Comment by Sawmyaa** [comment]
I can fix this

**Comment by amaranand360** [comment]
@ShivanshAr97  claim

**Comment by birm** [comment]
![Screenshot_20240122_130511_Firefox](https://github.com/camicroscope/caMicroscope/assets/4951803/26fdd297-6d91-4bc2-b7d6-9256fad7203f)
I think this issue is fixed.

**Comment by ShivanshAr97** [comment]
Yes it was fixed!
