### ISSUE TITLE
Reload button not responsive

### ISSUE THREAD

**Issue by ShivanshAr97** [camicroscope/caMicroscope#602]
**Describe the bug**

The reload button is not responsive in the slides column
![image](https://user-images.githubusercontent.com/96040322/225397818-2f12c852-aed3-4c11-8c28-77f703a97954.png)
![image](https://user-images.githubusercontent.com/96040322/225397895-2fbb1c79-cc40-462b-8187-d512b0a0ae7b.png)

**To Reproduce**
1. Go to 'Slides' section

**Expected behavior**
Something like this should appear:
![image](https://user-images.githubusercontent.com/96040322/225397512-aaab91fb-1ead-4129-9731-e7552fda76c8.png)
![image](https://user-images.githubusercontent.com/96040322/225397619-1564fb64-0751-4b29-bfe3-e81fc559e093.png)
![image](https://user-images.githubusercontent.com/96040322/225397679-98185231-da29-4586-89e3-9721b0b6f35b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Brave

**Smartphone (please complete the following information):**
 - Device: Redmi
 - Browser: Chrome

**Comment by ShivanshAr97** [comment]
I would like to work on this issue

**Comment by anushagupta1312** [comment]
Hey, I would like to work on this issue

**Comment by ShivanshAr97** [comment]
A PR has been opened for this @anushagupta1312

**Comment by anushagupta1312** [comment]
Okay
