### ISSUE TITLE
Major responsiveness issues on workbench navbar section

### ISSUE THREAD

**Issue by JayashTripathy** [camicroscope/caMicroscope#604]
**Describe the bug**
the navbar is weirdly behaving on small screen sizes

**To Reproduce**

1. Go to 'menu'
2. Click on 'Wokbench'
3. See bug

**Current behavior**

![image](https://user-images.githubusercontent.com/76092296/225428448-e762cbbd-540a-489e-bdb9-96e75dd089fc.png)

**Expected behavior**

https://user-images.githubusercontent.com/76092296/225429202-c1a6927f-a026-4d55-8aed-2a138097eb6d.mp4

- Device: [e.g. iPhone 12 mini]

**Comment by anushagupta1312** [comment]
Hey, I would like to work on this issue

**Comment by sourav8927** [comment]
i wanna work on this issue plz assign it to me

**Comment by slayer889** [comment]
can i work on this issue?
