### ISSUE TITLE
User-Guide is blank in ML Toolkit

### ISSUE THREAD

**Issue by ShivanshAr97** [camicroscope/caMicroscope#606]
**Describe the bug**
The Help/Guide appears blank, but I guess there was supposed to be some text there.
![image](https://user-images.githubusercontent.com/96040322/225600168-d132c225-2557-4cdc-833f-7d132c01df49.png)

**To Reproduce**
1. Go to 'Workbench' from the navbar.
2. Click on 'options'
3. Click 'Help/ User-Guide'

**Expected behavior**
Some text should appear here in my opinion. (I might be wrong)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Brave

**Smartphone (please complete the following information):**
 - Device: Redmi
 - Browser: Chrome

**Comment by anushagupta1312** [comment]
Hey, I would like to work on this issue

**Comment by Nischitkr** [comment]
Please assign me this issue

**Comment by ShivanshAr97** [comment]
> Please assign me this issue

It is more of a query man. What will you solve in this?👀

**Comment by Lollyrana** [comment]
please assign me this issue

**Comment by birm** [comment]
We don't usually assign issues, but do accept PRs :)

**Comment by Lollyrana** [comment]
Sir I am interested in this project but I don't know how to start
contributing. What should I do?
