### ISSUE TITLE
Improving the import.html UI/UX

### ISSUE THREAD

**Issue by ShivanshAr97** [camicroscope/caMicroscope#607]
**Describe the bug**
The import.html page currently looks off and does not match the theme of the website

**To Reproduce**
1. Go to 'import.html'
2. See error

**Expected behavior**
The user interface should have been a bit similar to the theme of the website.

**Screenshots**
![image](https://user-images.githubusercontent.com/96040322/225638705-e3ba947c-8cab-46cc-80e6-78beca9ca98f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Brave

**Smartphone (please complete the following information):**
 - Device: Redmi
 - Browser: Chrome

**Comment by ShivanshAr97** [comment]
Please assign it to me

**Comment by sourav8927** [comment]
i wanna work on it plz assign it to me

**Comment by ShivanshAr97** [comment]
I am working on it @sourav8927 A PR will be open by tonight

**Comment by sourav8927** [comment]
no prb i quiet this issue and i am woring on other
