### ISSUE TITLE
Overlapping / Not properly styled on class="card" in the workbench.html file

### ISSUE THREAD

**Issue by aniketsh22** [camicroscope/caMicroscope#615]
**Describe the bug**
There is overlapping  / not properly styled on class="card" in the workbench.html file when the user is viewing in the mobile layout.

**To Reproduce**

1. Go to 'Workbench' in the navbar in mobile layout
2. Then go to / Click on Select your own dataset.
3. See error

**Expected behavior**
class="card" in the workbench.html file should not be styled in a way as it can be seen overlapping on each other in mobile view, instead it should look like this
See the screenshot below:

<img width="381" alt="finaloutput" src="https://user-images.githubusercontent.com/89505839/226684986-d1aada7b-b8dd-4fd7-b976-504f14274623.png">

And 
Currently it is looking like this:
<img width="384" alt="1" src="https://user-images.githubusercontent.com/89505839/226685174-2459dc48-abd1-4491-ae52-7a178f0a67e2.png">

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome, Brave

**Comment by Prem-Mittal** [comment]
Could you assign me this issue?

**Comment by aniketsh22** [comment]
Hello @Prem-Mittal I have already worked on the issue and created a PR.

**Comment by Prem-Mittal** [comment]
ok
