### ISSUE TITLE
Improve the Landing Page UI

### ISSUE THREAD

**Issue by psankhe28** [camicroscope/caMicroscope#617]
Describe the bug
The landing.html page currently looks off and does not match the theme of the website

To Reproduce

Go to 'landing.html'
See error
Expected behavior
The user interface should have been a bit similar to the theme of the website.

Desktop (please complete the following information):

OS: Windows
Browser: Chrome, Brave

Smartphone (please complete the following information):

Device: Oppo
Browser: Chrome

**Comment by Prem-Mittal** [comment]
can I work on this issue?

**Comment by psankhe28** [comment]
I have already raised a pr. Please find another issue.
