### ISSUE TITLE
Fix UI of admin page

### ISSUE THREAD

**Issue by psankhe28** [camicroscope/caMicroscope#621]
Describe the bug
The admin.html page currently looks off and there is no even color in the navbar. The UI is not properly designed.

To Reproduce

Go to 'admin.html'
See error
Expected behavior
The user interface should have been even throughout the page.

Desktop (please complete the following information):

OS: Windows
Browser: Chrome, Brave

Smartphone (please complete the following information):

Device: Oppo, Iphone
Browser: Chrome

**Comment by arjunsaxena122** [comment]
_Can you assign this issue to me_

**Comment by Sawmyaa** [comment]
I can fix this in better way. Can you assign it to me?

**Comment by psankhe28** [comment]
I have already raised a pr. Please find another issue.
