### ISSUE TITLE
Improving the UI of EXPORT page !!

### ISSUE THREAD

**Issue by sourav8927** [camicroscope/caMicroscope#623]
**Export page of the navbar look like simple html page so improvement needed **!

screen short of the page :
![Screenshot (25)](https://user-images.githubusercontent.com/98399593/227276474-bd2d93e1-bef5-45ce-afef-717c3b6c4e7c.png)
![Screenshot (24)](https://user-images.githubusercontent.com/98399593/227276663-a925cd91-bc53-471b-8154-2c201150e7e5.png)

**Comment by sourav8927** [comment]
please assign it to me!

**Comment by Sankalp-sa** [comment]
@sourav8927 export page is updated check develop branch of the caMicroscope repo

**Comment by sourav8927** [comment]
I cant see the updated page   yet
