### ISSUE TITLE
Log in page doesn't have any designing

### ISSUE THREAD

**Issue by ShivamKaushik316** [camicroscope/caMicroscope#624]
**Describe the bug**
The login page doesn't have any designing . It just contains a Google Sign in button only .<br>

![image](https://user-images.githubusercontent.com/105926192/227457361-9a1bf8bb-f2bf-4ac7-88b3-3f5d9b7b9806.png)

**To Reproduce**
1. Go to  Sign up button.
2. Scroll down to "Already have an account ".
<br>
**Expected behavior**<br>
Should have some CSS and Javascript to work
<br>

![image](https://user-images.githubusercontent.com/105926192/227457471-fed79680-51f6-46ce-9172-b89cdda0baf0.png)

**Comment by ShivamKaushik316** [comment]
I have Fixed the Login page  in  PR #625.....Please review it

**Comment by Lokeshsri11** [comment]
https://user-images.githubusercontent.com/93934416/228732042-324b7442-60ea-4687-beb6-2d4c256c60c1.mp4

hello I also tried to fixed the Signup UI #625 please review it

**Comment by Gundeti-Anil** [comment]
Is this issue still open?

**Comment by kushalharshita** [comment]
Can work on this issue?

**Comment by Gundeti-Anil** [comment]
yes i can work on it
