### ISSUE TITLE
incorrect placeholder in user signup form 

### ISSUE THREAD

**Issue by moechadSayshi** [camicroscope/caMicroscope#626]
**Describe the bug**
In user signup form, below email input contain incorrect placeholder for password

**To Reproduce**
1. Go to 'signup.html'

**Screenshots**
![Screenshot (30)](https://user-images.githubusercontent.com/97633226/227569624-678b8579-dd8b-4754-9655-7f2aa591a166.png)

**Comment by soulpredator0** [comment]
Can you assign this issue to me??

**Comment by moechadSayshi** [comment]
> Can you assign this issue to me??

I have already raised PR

**Comment by Sawmyaa** [comment]
I can fix this can you assign it to me?

**Comment by birm** [comment]
This form has no password

**Comment by moechadSayshi** [comment]
> This form has no password

what its for then may I ask?

**Comment by birm** [comment]
This form is for a adding a user who will log in via google or another jwt including email. The second field is to set a filter on slides, such that a user and a slide must have one field in common, or the wildcard filter. I do think that the filter system needs a big rethink.

**Comment by Sawmyaa** [comment]
Can I work on this?

**Comment by moechadSayshi** [comment]
> This form is for a adding a user who will log in via google or another jwt including email. The second field is to set a filter on slides, such that a user and a slide must have one field in common, or the wildcard filter. I do think that the filter system needs a big rethink.

ok
