### ISSUE TITLE
Confusing Behavior of Enhance Unordered List Options

### ISSUE THREAD

**Issue by 3ngineer-AM** [camicroscope/caMicroscope#629]
The default selection for Enhance is Histogram Equalization, but since it's already selected when the page is loaded clicking it will not apply the Enhance Filter, the user has to click the drop icon to apply the Enhancement. However, clicking an Enhance option that is not already selected, like Sharpen, will apply the Filter on the first click but then will only apply it further if the drop icon is clicked. This confuses the user since they are led to believe that the Filter is applied when choosing one of the options, not when clicking the Enhance drop icon. 

There's 2 solutions to make behavior more consistent:

1. Do not let the Enhance Filter be applied when selecting which filter is desired (HE, Edge, Sharpen, Custom). Since the already selected Enhancement will not be applied if it is clicked further (If Sharpen icon is blue, and it is clicked Filter will not be applied), it is better if the Filter is applied by clicking the Enhance drop icon only. This will make it clear that the Unordered List is only for SELECTING the desired Filter, not APPLYING it. 

2. Implement ability to apply the the selected filter when clicking it, even if it is already selected (icon is blue). So if Sharpen is already selected for example, selecting sharpen again by clicking a 2nd time will apply the Enhance Filter to the slide. This tells the user that clicking the Enhance filter from the drop down list will both SELECT and APPLY it. 

**Additional context**
![image](https://user-images.githubusercontent.com/106180272/228369649-2f3dda0b-2067-461a-bd25-c97c9af9520d.png)
Here the Sharpen enhancement is already selected and was applied to the slide once it was selected. Selecting it again by clicking it will not apply the Sharpen Filter any further.

**Comment by adarsh7raj** [comment]
I want to work on this issue  ,but did not understand the issue completely, can you please provide me the steps to reproduce the issue .

**Comment by Sanskriti0805** [comment]
hello can i take up this one ?
