### ISSUE TITLE
 Create Custom Scrollbar for Improved User Experience

### ISSUE THREAD

**Issue by shivanisorte** [camicroscope/caMicroscope#633]
The default scrollbar in the application is functional but does not match the overall design aesthetic. Users may find it difficult to use and it may detract from the overall user experience. This custom scrollbar is intended to address these design issues and provide a more visually appealing and intuitive scrollbar that is consistent with the application's design.

I have created a customized scrollbar that matches the overall design of the application and provides users with a better user experience. It is easy to use, intuitive, and customizable to meet the needs of different users. I would like to integrate this custom scrollbar into the application to enhance the user experience.

Below is a snippet of the Customized Scrollbar

![Screen Recording - Made with FlexClip](https://user-images.githubusercontent.com/69205415/228822025-b0ef27d0-0fcf-4efe-8490-760f5b287fa1.gif)

**Comment by gaurab-khanal** [comment]
@shivanisorte  Can you help me to run  this locally?

**Comment by shivanisorte** [comment]
Yeah sure. Since this is built using vanilla HTML, CSS, and JS, you can run this directly by opening index.html with Live Server or by copying its file path into a browser.

**Comment by gaurab-khanal** [comment]
> Yeah sure. Since this is built using vanilla HTML, CSS, and JS, you can run this directly by opening index.html with Live Server or by copying its file path into a browser.

Thanks. I actually run it using this way. I was just wondering if that was right or wrong.
