### ISSUE TITLE
Lazier Tile Fetching On Zoom

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#648]
Currently, nearly instantaneous zooms from min resolution to max resolution seem to include all intermediate resolution levels.
We might want to change the order in which tiles are retrieved, and even skip them.

This might involve overriding the behavior of openseadragon's jobs, see https://openseadragon.github.io/docs/OpenSeadragon.ImageLoader.html

**Comment by YuvBindal** [comment]
Hey I would like to take up this issue, seems interesting!

**Comment by birm** [comment]
Is there anything we can do to help you get started looking into this?

**Comment by birm** [comment]
Closed due to lack of activity.
