### ISSUE TITLE
Add the option to access files that are already in the server

### ISSUE THREAD

**Issue by maferoaloaiza** [camicroscope/caMicroscope#649]
I am using your Hosted setup, and it seems to have all the requirements we need for our project. However, I would like to be able to access the image files that are already stored on the server instead of having to upload them on the UI. I saved the images into the `/images` folder that the app uses to store the images, but they are not matched into the mongo db and are not visible in the UI. Is there a way I can see these existing images and be able to annotate them in the data viewer?

**Comment by birm** [comment]
This is what https://github.com/camicroscope/SlideLoader/blob/master/SlideUtil.py is for; it extracts the metadata from the images and adds them to mongo. You can use `docker exec -it ca-load bash` to get a shell inside of the loader container.

**Comment by maferoaloaiza** [comment]
Thanks! That looks very helpful. I will let you know if I find any issues when using that tool.
