### ISSUE TITLE
Navbar Redesign

### ISSUE THREAD

**Issue by Apurv428** [camicroscope/caMicroscope#669]
**Summary:** 

The current navbar lacks visual appeal, prompting consideration for a redesign or utilizing the existing navbar design used in other websites.

![image](https://github.com/camicroscope/caMicroscope/assets/84929607/518b7696-e781-4440-8743-9ba84c5120f0)

**Background:** 

Improving the user interface is crucial for a seamless experience across all caMicroscope-related websites. Consistency in design is a key goal.

**Implementation:**

I suggest adopting a uniform design, resembling the example below:

![image](https://github.com/camicroscope/caMicroscope/assets/84929607/c78fac9c-d66e-4c73-ab37-b41d39a7cd4e)

**Expected Impact:** 

The proposed design aims to establish a consistent navbar across various caMicroscope websites, enhancing the user interface with a color scheme in line with the overall theme.

**Comment by Apurv428** [comment]
@birm , could you assist with this? Is this approach deemed suitable, or should we consider alternative solutions? Your insights on the matter would be valuable.

**Comment by Apurv428** [comment]
@adarsh7raj This can help you: [Link](https://github.com/camicroscope/caMicroscope?tab=readme-ov-file#hosted-setup)

**Comment by Happyashbunny** [comment]
@Apurv428 @adarsh7raj I'd also like to contribute on this issue

**Comment by Apurv428** [comment]
@gupta-sujal I have raised the issue and am currently awaiting the administrator's response. Upon approval, I will proceed with the implementation.

**Comment by Akhilesh-max** [comment]
@birm 
I’ve been working on some enhancements to the existing navbar. Could you please take a look and let me know if it meets your expectations?

![Screenshot 2024-03-05 at 11 32 45 AM](https://github.com/camicroscope/caMicroscope/assets/124369508/3aba28d2-6e2e-4998-b75f-d64ce45f1992)

**Comment by birm** [comment]
Closed due to lack of activity.
