### ISSUE TITLE
Explore the use of OSD SVG plugin rather than our in-house SVG handler

### ISSUE THREAD

**Issue by sharmaashish** [camicroscope/caMicroscope#68]
https://github.com/openseadragon/openseadragon/issues/1225

We should evaluate one of the two options suggested here, and compare it's performance with our own in-house solution from 2013.

**Comment by birm** [comment]
Sidesplit uses this; https://github.com/camicroscope/caMicroscope/blob/release/js/Helpers/SideSplit/openseadragon-canvas-overlay.js

**Comment by birm** [comment]
We're using it!
