### ISSUE TITLE
DIACOM Server Access Error in Slides Tab

### ISSUE THREAD

**Issue by Akhilesh-max** [camicroscope/caMicroscope#694]
I encountered an issue while trying to access the DIACOM server via the slides tab. An error message is displayed both on the console and the screen, indicating that the server is unconfigured.

<img width="540" alt="Screenshot 2024-03-06 at 7 05 15 PM" src="https://github.com/camicroscope/caMicroscope/assets/124369508/1c38cabe-5a21-4703-9614-67fc466f0639">

Steps to Reproduce:

Navigate to the slides tab.
Click on the DIACOM button.
Observe the error message in the console and the prompt on the screen indicating an unconfigured server.

Expected Outcome: 
The server should be properly configured, allowing seamless access to the DIACOM server from the slides tab.

**Comment by Lahitan** [comment]
Hi @Akhilesh-max  i would like to work on this project too, I am an Outreachy applicant, but I am finding it difficult navigating to the community or group of other applicants for easy collaboration.

Please can you put me through on how I can start contributing to this project.

Thank you

**Comment by Akhilesh-max** [comment]
@Lahitan I feel, the first step would be to setup the development environment. 
Please use the caMicroscope docker distribution and also don't forget to make the `develop.yml` in distro to point to your local caMicroscope and carcel repo.

Distro : https://github.com/camicroscope/distro
Carcel : https://github.com/camicroscope/Caracal

**Comment by Lahitan** [comment]
@Akhilesh-max  Thank you for the update
