### ISSUE TITLE
 Feature/ Responsiveness enhancement in home page in mobile or tablet screens 

### ISSUE THREAD

**Issue by SakshiVar** [camicroscope/caMicroscope#697]
**Summary:** 
Website is not responsive in mobile and tab view.

**Background:**
 The requested style change will enhance user experience and readability.

**Use Cases:** 
This feature will give a better user experience and enhance readability

**Comment by mhdamaan79** [comment]
I'd love to work on this! I'm an Outreachy May 2024 applicant. Please assign this issue to me.

**Comment by Akhilesh-max** [comment]
@SakshiVar Thanks! I'm little uncertain if this is the right repo for the issue you have raised.

**Comment by SakshiVar** [comment]
> @SakshiVar Thanks! I'm little uncertain if this is the right repo for the issue you have raised.
Yes, I think it's the right repo.

**Comment by Akhilesh-max** [comment]
@SakshiVar, can you locate the code related to the website for which you’ve shared screenshots in this repository?
