### ISSUE TITLE
Feature/ In SignUp page , the SignUp and Feedback buttons are overlapping , on hovering!

### ISSUE THREAD

**Issue by SakshiVar** [camicroscope/caMicroscope#699]
**Describe the bug**
In Signup page , SignUp  and Feedback buttons are overlapping ,on hovering

**To Reproduce**
1. Go to 'Home Page'
2. Click on 'SignUp'
3. Hover on 'Feedback' or 'SignUp'

**Expected behavior**
 There should be some gap between SignUp and Feedback Button .The requested style change will enhance user experience and readability.

**Screenshots**
![Screenshot 2024-03-08 114855](https://github.com/camicroscope/caMicroscope/assets/112648026/c2737278-67d0-42c2-9efd-e16b3e760ed1)
![Screenshot 2024-03-08 114924](https://github.com/camicroscope/caMicroscope/assets/112648026/1c35328d-063c-40f6-acf0-29793c044dcf)

**Desktop**
 - OS: Windows
 - Browser : Microsoft Edge

@birm ,Please assign this task to me under Outreachy 2024. I'm working on the code.

**Comment by Ayesh-07** [comment]
Dear SakshiVar ! 
I'm Ayesha Nudrat, an applicant for Outreachy. I'm reaching out regarding the GitHub issue #699 titled "Feature/ In Signup page , the SignUp and Feedback buttons are overlapping , on hovering!" After reviewing the details, I'm confident in my ability to efficiently contribute to resolving this matter.

**Comment by birm** [comment]
solved with #702
