### ISSUE TITLE
Signup Page: Improve User Experience with Button Placement and Consistent Navbar

### ISSUE THREAD

**Issue by SisiVero** [camicroscope/caMicroscope#730]
Summary:
Propose changes to the signup page for improved user experience and consistency.
Background:

Background:

The current signup button placement might not be optimal for user flow.

Lack of navbar uniformity between the landing page and signup page can create confusion.

Use Cases:

Improved User Experience: Placing the signup button above the "Already have an account?" text leverages the Gestalt principle of proximity, which suggests that users perceive closer elements as related. This can guide users towards the primary action (signing up) and improve the overall signup flow.

Enhanced Consistency: Maintaining a consistent navbar design across the landing page and signup page reinforces learnability and reduces cognitive load for users. This aligns with the design principle of uniformity, which emphasizes the importance of consistent visual elements for a cohesive user experience.

Implementation:

Reposition the signup button above the "Already have an account?" text on the signup page.

Ensure the navbar on the signup page matches the design and functionality of the navbar on the landing page.

Expected Impact:

Clearer User Journey: A more intuitive signup flow with the signup button placed prominently can lead to higher signup completion rates.

Reduced User Confusion: Consistency in navbar design across pages fosters a more unified experience and reduces the learning curve for users navigating the platform.

For reference:

The Gestalt principle of proximity: https://en.wikipedia.org/wiki/Gestalt_psychology

Design principle of uniformity: https://www.usability.gov/

**Comment by bruno-noir** [comment]
Kindly check it out and let me know if any adjustments are needed.

**Comment by birm** [comment]
solved with #784
