### ISSUE TITLE
Reload button margin needed in slides page(table.html)

### ISSUE THREAD

**Issue by gbengaoluwadahunsi** [camicroscope/caMicroscope#737]
The reload button is too close to the next button, lacking proper spacing or margin between them.

To Reproduce

Navigate to the  table.html page containing the upload button and the next button.
Observe the positioning of the reload button relative to the next button.
Expected behavior
There should be adequate spacing or margin between the upload button and the next button to improve readability and user experience.

Screenshots
Attached

Desktop (please complete the following information):

OS: Windows 10
Browser: Google Chrome
Version: 98.0.4758.102
Smartphone (please complete the following information):
Infinix

Additional context
The issue may be addressed by adding CSS styling to create a margin between the reload 
![reload-dicom](https://github.com/camicroscope/caMicroscope/assets/77133593/3da4b877-dc1d-4ba0-8e9c-4f1f203c3442)
button and the next button. Adjustments to the layout or positioning of the buttons may also be necessary to ensure proper spacing and alignment.

**Comment by birm** [comment]
seems to be fixed with #737
