### ISSUE TITLE
Upload button not added in the slides page in caMicroscope repo app(upload button present in Distro repo but absent in caMicroscope repo  equivalent)

### ISSUE THREAD

**Issue by gbengaoluwadahunsi** [camicroscope/caMicroscope#739]
Summary: This proposal aims to add an upload button to the slides page in the caMicroscope repository.

Background: The upload button is a crucial feature for users who want to upload new slides to the caMicroscope platform. Currently, the lack of an upload button on the slides page in the caMicroscope repository limits users' ability to easily add new slides to the platform. By adding this feature, we enhance the usability and functionality of the caMicroscope platform, providing users with a seamless experience for uploading slides.

Use Cases:

Researchers and medical professionals can easily upload new slides to the caMicroscope platform directly from the slides page.
Users who acquire new slide images can quickly add them to their collections without navigating to a separate upload section.
Administrators can efficiently manage slide uploads and monitor the addition of new content to the platform.
Implementation:

Add an upload button to the slides page interface, preferably near the top for easy access.
Implement functionality to handle file uploads, including validation and processing of uploaded slide images.
Integrate the upload button with the backend server to store uploaded slide images securely.
Ensure compatibility with different file formats commonly used for slide images, such as TIFF or JPEG, dicom, and 
![slide](https://github.com/camicroscope/caMicroscope/assets/77133593/48510d70-91e2-4ddd-a9bf-3e636b142155)
![slide2](https://github.com/camicroscope/caMicroscope/assets/77133593/026e4ecb-3b84-46a6-af4c-dfe990480e2a)
svs.
Implement error handling and feedback mechanisms to inform users of successful or failed upload attempts.

Expected Impact:

Improved user experience: Users will find it easier and more convenient to upload new slides directly from the slides page, reducing the time and effort required to add content to the platform.
Increased engagement: The availability of an upload button encourages users to contribute new slide images to the platform, fostering community engagement and collaboration.
Enhanced functionality: Adding an upload button enhances the platform's feature set, making it more versatile and accommodating a broader range of user needs.
Additional Notes:

The addition of an upload button aligns with the caMicroscope platform's goal of providing a comprehensive and user-friendly solution for viewing and managing slide images.
Consider user feedback and input during the implementation process to ensure that the upload button meets users' expectations and requirements.
Regularly test and iterate on the upload feature to address any usability issues or technical challenges that may arise during development.

**Comment by CodebyCc** [comment]
Can i be assigned to this issue Please?

**Comment by gbengaoluwadahunsi** [comment]
Hello, this is an issue we are reporting, our mentor @birm will have to go
through each issue, issue/issues that will be approved can be included in
the contribution file and anyone can work on the bug/feature.

In summary, we can't assign or work on an issue that is not approved.

**Comment by ujjwaldubey1** [comment]
@gbengaoluwadahunsi was this present in the previous version of this repo. Because i have seen some youtube video where upload button was showing in that video .

**Comment by birm** [comment]
@ujjwaldubey1 did you run distro recently and still encounter this issue?

**Comment by ujjwaldubey1** [comment]
@birm Yes, I ran the container recently, and the issue still occurs.
