### ISSUE TITLE
Upload model form on view page needs adjustment on mobile view

### ISSUE THREAD

**Issue by gbengaoluwadahunsi** [camicroscope/caMicroscope#741]
Describe the bug
The upload model form UI on the image viewer page appears when viewed on mobile devices.

To Reproduce

Access the image viewer page on a mobile device.
Attempt to open the upload model form.
Notice that the form elements are misaligned, overlapping, or difficult to interact with.
Expected behavior
The upload model form should display correctly and be fully functional on mobile devices, allowing users to easily upload images without any usability issues.

Screenshots
Attached

Desktop (please complete the following information):

OS: Windows 10
Browser: Google Chrome
Version: 98.0.4758.102
Smartphone (please complete the following information):
Infinix
![model-viewer](https://github.com/camicroscope/caMicroscope/assets/77133593/60333d7c-190a-4fd5-a81d-9f496f515710)
![mobile-viewer2png](https://github.com/camicroscope/caMicroscope/assets/77133593/c04c242b-5539-483d-ba79-1ec58594dd5f)

Additional context
The distorted UI of the upload model form on mobile devices hinders the user experience and may discourage users from uploading images using their smartphones or tablets. This issue needs to be addressed to ensure that the image viewer page is accessible and usable across all devices.

**Comment by HRIDYANSHU054** [comment]
Hi @gbengaoluwadahunsi I have solved this issue, can you review my PR
