### ISSUE TITLE
Mobile Tilt Mode Functionality Button Misalignment

### ISSUE THREAD

**Issue by barchakuz** [camicroscope/caMicroscope#748]
**Description:**
Currently, the website structure encounters a critical issue when accessed via mobile devices in tilt mode. The functionality button shifts out of the designated design structure, residing in an unoccupied left area where neither the header nor the footer reaches. This not only undermines the structural integrity of the website but also significantly hampers user experience (UX), making it challenging for users to locate the button in its unexpected position.

**To Reproduce:**
Access the website on a mobile device.
Activate tilt mode or tilt the device to simulate such a view.
Navigate to the section where the functionality button is expected to appear.
Observe as the button moves out of the intended design structure into the vacant left area.
Expected Behavior:
The functionality button should remain within the designated design boundaries, irrespective of the device's orientation or tilt mode. It should be consistently positioned where users expect to find it, ensuring a seamless and intuitive user experience.

**Screenshots:**
Attached screenshots demonstrating the misalignment of the functionality button in tilt mode.

**Root Device:**
OS: Win 10
Browser:Chrome
Version: 24

**Tested Device 1:**
Device: Iphone 14 Pro Max
OS: iOS8.1
Browser Safari
Version 5.1
_Normal View_
![In](https://github.com/camicroscope/caMicroscope/assets/66128370/3cd1d87d-53bf-4673-a615-d5ed3bf59661)

_Tilted Screen View_
![Iphone](https://github.com/camicroscope/caMicroscope/assets/66128370/1af30b5e-dec1-452d-bd56-c9c39f17f0cf)

**Tested Device 2:**
Device: samsung galaxy s24
OS: Android 14
Browser Crome
Version 22
_Normal View_
![Normal](https://github.com/camicroscope/caMicroscope/assets/66128370/c9840a08-3a7f-49e1-880e-fad73c2f233f)
_Tilted Screen View_
![Samgun](https://github.com/camicroscope/caMicroscope/assets/66128370/5e45aba3-2e90-4282-9ad8-bf2ff8a1a1c9)

**Additional Context:**
This issue not only affects the aesthetic appeal of the website but also has significant implications for user interaction and engagement. Resolving this bug is crucial to ensuring a consistent and delightful user experience across all devices and orientations.

**Comment by robel16** [comment]
@barchakuz can i work on this?
