### ISSUE TITLE
REDESIGN OF THE NAVIGATION BAR AND HOME PAGE FOR BRAND CONSISTENCY.

### ISSUE THREAD

**Issue by Khadijaarike** [camicroscope/caMicroscope#751]
Summary:
I propose redesigning the navigation bar and home page for consistency across the brand CaMicroscope.

Background:
Currently, the designs on the landing pages/websites [localhost](http://[localhost](http://localhost:4010/apps/landing/landing.html):4010/apps/landing/landing.html) and [https://camicroscope.org/](url)  are different and are not consistent with each other, different colours and fonts are used. Brand consistency is a crucial aspect of building a successful and recognizable brand and plays a significant role in shaping customer perception and building brand loyalty, this is why i decided to propose these changes.
![image of websites](https://github.com/camicroscope/caMicroscope/assets/161035744/b939db8e-8561-4ae9-ac3a-01e604b4bda9)

Use Cases: 
**Colour and font**
The colour used on the landing page [caMicroscope](https://camicroscope.org/) colour is **#9a2ca0** and the font used is **Poppins**. On the other website (http://[localhost](http://localhost:4010/apps/landing/landing.html):4010/apps/landing/landing.html) there is no consistency and the font used is **Arial**. 

However, the colour used #9A2CA0 on the background #FFFFFF has poor contrast for small letters and failed WCAG STANDARD AAA, I recommend changing it to **#742178** as it passed for both small and big letters for WCAG STANDARD AA and AAA. The right colour contrast makes your page accessible to a large group of people such as colour-blind, nearsighted or just users of an older age.
![colour constrast and accessibility check 1](https://github.com/camicroscope/caMicroscope/assets/161035744/3887b75a-d4ed-4178-8036-01839dd4a0b1)
![colour constrast and accessibility check 2](https://github.com/camicroscope/caMicroscope/assets/161035744/b2afd3c7-4986-4ad0-a587-2df66ca62510)

**Accessibility**
The images do not have accessible text that is visible to screen readers, implementing alt text will improve the accessibility of the page, especially for screen readers.

**Aesthetics**
Elements on the page were not aesthetically pleasing because the elements were not balanced on the page, and had unequal spacing.

**Implementation:** 
These are screenshots of the proposed redesign changes from my Figma file. Consisting of the light mode and dark mode home page, and also the design with ALT text.
 
![redesigned dark and light](https://github.com/camicroscope/caMicroscope/assets/161035744/bd8b03fc-b140-4955-b47e-f3c2daafb7be)
![redesigned light mode with alt text](https://github.com/camicroscope/caMicroscope/assets/161035744/8ed4e057-a664-4ad7-a007-6474a810e92a)

**Expected Impact:** 
The redesigned navigation bar on the website will ensure brand consistency.

The redesigned home page, improves the balance and hierarchy of the page.

The included dark mood option for the home page can help users reduce eye strain, also for users with dyslexia or visual processing disorder who find it tough to interpret black text on a white background.

Alt text included to images will help screen readers.

**Additional Notes:** 
This is the link to the figma file [https://www.figma.com/file/mBg74uj7xVPxMo4A0iOOVP/outreachy-project?type=design&node-id=0%3A1&mode=design&t=UlosQYHD3iH1GHkB-1.](url)

**Comment by izzdwizz** [comment]
Hi! If this hasn't been worked on yet, I would like to be assigned to it. Thank you!

**Comment by Khadijaarike** [comment]
hi @izzdwizz, I am sorry it is not in my power to assign issue reports. Also, mentor @birm had mentioned in a response, I quote "We don't usually assign issue reports, so we'll look at any open pulls". I hope this helps
