### ISSUE TITLE
Adjustment of the UI of the slides selection button in tablet and mobiile view

### ISSUE THREAD

**Issue by gbengaoluwadahunsi** [camicroscope/caMicroscope#752]
Describe the bug
In both table and mobile views, the user interface (UI) of the slides selection button needs adjustment.

To Reproduce

Access the application in either tablet or mobile view.
Navigate to the slides selection button.
Observe the current appearance and functionality.
Expected behavior
The slides selection button should be properly adjusted to fit the screen size and provide easy access to slide selection options without overlapping or misalignment.

Screenshots
Attahced

Desktop

OS: [e.g. Windows 10]
Browser: [e.g. Google Chrome]
Version: [e.g. 99.0.4844.51 (Official Build) (64-bit)]

Smartphone
Infinix 
![Uploading tab-bug.png…]()

Additional context
The issue pertains to the slides selection button specifically in both table and mobile views. The adjustment is necessary to enhance user experience and ensure proper functionality across different screen sizes.

**Comment by ujjwaldubey1** [comment]
@gbengaoluwadahunsi  Screenshot is  not opening ?
