### ISSUE TITLE
Adjustement need on the drop down option bar for the slides selection button on tablet and mobile view

### ISSUE THREAD

**Issue by gbengaoluwadahunsi** [camicroscope/caMicroscope#753]
Describe the bug
In both tablet and mobile views, the user interface (UI) of the slides selection button needs adjustment.

To Reproduce

Access the application in either tablet or mobile view.
Navigate to the slides selection button.
Observe the current appearance and functionality.

Expected behavior
The slides selection button should be properly adjusted to fit the screen size and provide easy access to slide selection options without overlapping or misalignment.

Screenshots
Attached

Desktop

OS: Windows 10
Browser: Google Chrome
Version:  99.0.4844.51 (Official Build) (64-bit)

Smartphone
Infinix
![tablet](https://github.com/camicroscope/caMicroscope/assets/77133593/0df7d83c-f6f9-4311-8dc9-091d5213700d)

Additional context
The issue pertains to the slides selection button specifically in both table and mobile views. The adjustment is necessary to enhance user experience and ensure proper functionality across different screen sizes.

**Comment by Lahitan** [comment]
please assign this issue to me

**Comment by gbengaoluwadahunsi** [comment]
Pls you don't need to be assigned to any issue, @birm said it's an open
source project, anyone can go ahead and pick an open issue to work on.

Thanks & Regards.

**Comment by Lahitan** [comment]
Okay thank you

**Comment by gbengaoluwadahunsi** [comment]
You are welcome
