### ISSUE TITLE
Create your dataset page needs UI adjustment on tablet view

### ISSUE THREAD

**Issue by gbengaoluwadahunsi** [camicroscope/caMicroscope#754]
Describe the bug
The UI of the dataset page needs adjustment specifically for tablet view.

To Reproduce

Access the dataset page on a tablet device.
Navigate through the page.
Observe the layout and functionality.
Notice any elements that appear misaligned or overlapping.
Expected behavior
The dataset page should display properly on tablet devices, with all elements appropriately sized and positioned for optimal viewing and interaction.

Screenshots
Attached
![dataset](https://github.com/camicroscope/caMicroscope/assets/77133593/9861fa58-a66b-4048-a2fa-082d4ba6e01c)

Desktop

OS: Windows 10
Browser: Google Chrome
Version: 99.0.4844.51 (Official Build) (64-bit)
Smartphone

Device: iPad Pro
OS: iOS 15.2
Browser: Safari
Version: 15.2
Additional context
The issue is specific to tablet view and requires adjustments to ensure a seamless user experience across different devices.

**Comment by shailpujan88** [comment]
Hey, I'm interested in tackling this issue. Could you please assign it to me? Thanks!
