### ISSUE TITLE
Duplication of functionality  ---Help section of the workbenchhtml page

### ISSUE THREAD

**Issue by gbengaoluwadahunsi** [camicroscope/caMicroscope#755]
The Help section of the workbench HTML page contains duplicated functionality with both a close button and a "fa timees" button, leading to redundancy.

To Reproduce

Navigate to the Help section of the workbench HTML page.
Observe the presence of both the close button and the "fa timees" button.
Attempt to use either of the buttons.
Notice the redundancy in functionality.
Expected behavior
The Help section of the workbench HTML page should ideally have only one button for closing the section, providing a streamlined user experience.

Screenshots
Attached

Desktop

OS: Windows 10
Browser: Google Chrome
Version: 99.0.4844.51 (Official Build) 64-bit

Smartphone
Infiinix

Additional context
The presence of both the close button and the "fa times
![help](https://github.com/camicroscope/caMicroscope/assets/77133593/5fb73c44-0a70-4926-9014-90eec1ad9952)
" button in the Help section can confuse users and lead to unnecessary repetition in functionality. Removing one of these buttons would streamline the user interface and improve user experience.

**Comment by rchaurase** [comment]
i have resolve this issue and there was some in options dropdown , dropdown list was not fully visible, i have resolve both issue, please review my pr.

**Comment by gbengaoluwadahunsi** [comment]
Hello @rchaurase 
Please , I am a contributor like you and only @birm has the power to resolve issues and  merge PR.

**Comment by rchaurase** [comment]
Okay thank you for reply .
