### ISSUE TITLE
🐛 Help button on workbench not displaying the user guide 

### ISSUE THREAD

**Issue by hannyP** [camicroscope/caMicroscope#757]
**Describe the bug**
when you click on the help button it should display the user guide but it didn't showing the following error
![Screenshot 2024-03-13 152336](https://github.com/camicroscope/caMicroscope/assets/141145167/e4b0d990-f84f-4b8b-a407-2cd507421484)

**To Reproduce**
1. Go to  workbench
2. Click on option and click on help
3. See error

**Expected behavior**
should display the readme guide 

**Screenshots**
![Screenshot 2024-03-13 152309](https://github.com/camicroscope/caMicroscope/assets/141145167/dbc97b73-c764-45bd-9eb1-1daf4849ec5a)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser edge

**Comment by Akhilesh-max** [comment]
It's been fixed and there's a PR open for the same 
 #683
