### ISSUE TITLE
Non-updated year in footer of apps/table.html

### ISSUE THREAD

**Issue by shusonialumnwi** [camicroscope/caMicroscope#760]
**Describe the bug**
They displayed year in the footer is a non-dynamic 2021, with this updated year, it suggests that camicroscope has not been updated since 2021 or is not being maintained. An expected behavior would have been for the year to reflect the current year.

**To Reproduce**
1. Go to 'http://localhost:4010/apps/table.html'
3. Scroll down to 'the end of the page'
4. See that the year displayed on the footer is 2021

**Expected behavior**
Rather than 2021, the copyright text in the footer should display the current year.

**Screenshots**
![Screenshot from 2024-03-13 12-39-38](https://github.com/camicroscope/caMicroscope/assets/162718653/3f6c0e36-b337-4ef7-8381-fceacd107ea8)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome

**Comment by arghya-align-pix-design** [comment]
i have solved this and put a pull request.
