### ISSUE TITLE
Unclear step in "Upload New Slide" dialog

### ISSUE THREAD

**Issue by shusonialumnwi** [camicroscope/caMicroscope#762]
**Describe the bug**
Step 3 of "Upload New Slide" is not clear

**To Reproduce**
1. Go to 'http://localhost:4010/apps/table.html'
2. Click on 'Upload'
3. See error: Step 3 under "Steps for Uploading" reads "... button to **get check** a preview of the slide"

**Expected behavior**
The message should clearly describe what happens in that step. It should does be something like: "... button to get a preview of the slide"

**Screenshots**
![Screenshot from 2024-03-13 13-47-18](https://github.com/camicroscope/caMicroscope/assets/162718653/8300c7dd-6fd5-4627-81b8-665b0f5a8636)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version 122.0.6261.128 (Official Build) (64-bit)

**Comment by Akhilesh-max** [comment]
#808
