### ISSUE TITLE
identification of inconsistency in form validation errors across the platform.

### ISSUE THREAD

**Issue by DIANAAJAMBO** [camicroscope/caMicroscope#764]
**Describe the bug**
Firstly, on certain pages, such as the sign-up page, the form validation error appears as a quote and an an alert 
indicating a required attribute in an input field. However, there's an issue with the placement of this error message as it is not consistent with the form validation on the slides page.
The slides page too has 2 inconsistent form validation errors. one in red (file name validation error) and below the input field, another error is below the blue arrow button and in black but relating to the slide name field which is not next to it. Users have to scroll to find it because it's not immediately visible in the viewport.
This inconsistency in color and visibility could lead to user frustration and confusion.

**To Reproduce**
**For the slides page**
1.Go to the slides page.
2.Click on the "Upload" button.
3.Select a file to upload.
4.Scroll down to locate the blue arrow.
5.Click on the blue arrow to proceed.
6.Ensure that both the "file name field "and "slide name field" are left empty.
7.Observe the error message as displayed in the picture.

**For the signup page**
1.Go to the sign-up page.
2.Click on the "Sign Up" button without entering an email.
3.Observe the initial alert, which is a validation error.
4.Click "OK" to dismiss the alert.
5.Observe the subsequent error message displayed in the form of a quote, indicating HTML validation.

**Expected behavior**
 That form validation error messages should be uniformly styled, appropriately placed, and clearly visible across all pages and forms.

**Dell latitude Laptop 14 inches **
 - Windows Operating System
 - Browser Chrome
 - Version 122.0.6261.95 
![Screenshot (340)](https://github.com/camicroscope/caMicroscope/assets/124655553/c0a69200-ce79-4399-8c4c-e84f9347b7a0)
![Screenshot (339)](https://github.com/camicroscope/caMicroscope/assets/124655553/54e8a6fd-426d-465d-9a15-2b23405c63ef)

**Comment by sarahannie** [comment]
#884  worked on the email validation for the signup page
