### ISSUE TITLE
Login page does not exist

### ISSUE THREAD

**Issue by SanjanaSogimatt** [camicroscope/caMicroscope#771]
**Describe the bug**
When the user clicks on the "Already have an account?" link at the bottom of the sign up page, It redirects to an empty page instead of asking the user to login.

**To Reproduce**
1. Go to 'sign up'
2. Click on 'Already have an account?'

**Expected behavior**
When user clicks on the link. It should redirect to login form when the user can login

**Desktop:**
 - OS: WIndows 11
 - Browser: Microsoft edge

**Comment by Sky-De** [comment]
Hi @SanjanaSogimatt please assign this to me, I would like to address this issue
