### ISSUE TITLE
Misalignment of components on mobile

### ISSUE THREAD

**Issue by izzdwizz** [camicroscope/caMicroscope#783]
**Describe the bug**
On mobile view, the positions of the input fields and buttons appear to be cramped up, undermining the structural integrity of the website.

**To Reproduce**

1. Navigate to the table.html page containing the collection button, the "slides/page" button, reload button and the search input field.
2. Bring up dev tools (F12 on Windows), select a mobile screen resolution such as the iPhone 12 pro.
3. Observe the positioning of the buttons and the input f

**Expected behavior**
There should be proper alignment of the buttons and the input field, in some sort of column format as to improve user experience.

**Screenshots**
![image](https://github.com/camicroscope/caMicroscope/assets/71931658/09ea6ea0-5138-441f-8050-6d2e194dec90)

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Google Chrome
Version: 122.0.6261.129 

**Smartphone (please complete the following information):**
iPhone 12 pro

**Additional context**
The issue may be addressed by adding CSS styling to create a media query targeting the mobile resolution and applying a flex direction of column to the element containing the affected components.

**Comment by rchaurase** [comment]
i have solve this problem already .
