### ISSUE TITLE
Image uploader changes ndpi file extension to dpi.

### ISSUE THREAD

**Issue by bcli4d** [camicroscope/caMicroscope#79]
When a Hamamatsu file with extension ndpi is uploaded using the Image Uploader, the resulting file has a dpi extension. The file is then not recognized by the server as an openslide compatible format.

I am running sbubmi/quip_*:1.0 images.

**Comment by birm** [comment]
I want to reproduce this error; do you have any files I could try with?

**Comment by sharmaashish** [comment]
Take a .ndpi file from here [http://openslide.cs.cmu.edu/download/openslide-testdata/Hamamatsu/](http://openslide.cs.cmu.edu/download/openslide-testdata/Hamamatsu/)

**Comment by birm** [comment]
Renaming the extension to .svs seems to work as a temporary workaround. Looking now into why this happens.

**Comment by sharmaashish** [comment]
Not a fix. Looks like somewhere the file is being renamed.

**Comment by birm** [comment]
Error found, https://github.com/camicroscope/ImageLoader/pull/16; tested on dragon.

**Comment by birm** [comment]
Pulled to master on the imageloader repo; you can pull the change to your branch, which will fix this issue.
