### ISSUE TITLE
MAINTAINING UNIFORMITY IN BRAND COLOUR, FONT, AND COLOUR ACROSS ALL WEBSITES AND APP TO ESTABLISH A COHESIVE AND POSITIVE BRAND IDENTITY FOR CAMICROSCOPE.

### ISSUE THREAD

**Issue by Khadijaarike** [camicroscope/caMicroscope#795]
**Summary:** 

I propose the brand should maintain specific brand colors and font across all websites and apps

**Background**

Brand identity is a visual representation of a brand that uses elements like color and logo that help the users create a distinct image in their minds and help them remember a brand better. Color, in particular, plays a crucial role in shaping user behavior as it is often the first thing noticed by the target market.
Take Facebook, for instance, which is synonymous with the color blue. This hue permeates the entire brand experience, from the website design to the logo and user interface. Similarly, Starbucks uses green across its stores, employee uniforms, digital platforms, and packaging, creating a consistent brand image.

 Colours are a great brand identifier and they must relate to your brand. The lack of consistency in the colours across CaMicroscope sites and apps can seem unprofessional and may have a negative impact on your customers' perception of your brand.

**Use Cases:**

 Going through CaMicroscope sites and Apps, I could identify up to 9 different colours (#942CA0, #7C8698,#212529,#24A9F6,#FFE648,#365F9C,#17A2B8,#343A40,#157347,#0D6EFD,#0B5ED7,and unfortunately, they don't complement each other well. 
The logo colour is a shade blue and yellow (#24A9F6 and# FFE648), but **there is no consistent use of these colors throughout the sites and apps**. **The logo is not prominently displayed across sites and Apps,** Also **there is no consistency in the font used on the websites,** Arial on one and Poppins on the other.  This inconsistency could confuse users and negatively impact their perception of your brand. Let's work on creating a cohesive look and feel across all platforms for a stronger brand identity.

**Implementation:**
 I propose that a color palette should be created that should be used across sites and the app of Camicroscope to ensure uniformity. Also, the brand logo should be prominently and consistently used on sites and apps.

![colour scale](https://github.com/camicroscope/caMicroscope/assets/161035744/400ded38-f2c8-4ef3-92fb-596f506dfc59)

**Expected Impact:**  
Brand identity reinforces brand associations and enhances recognition. users will be able to easily recognize and identify this brand.

**Additional Notes:** [Any additional context, information, or references that can support your proposal.
](https://designcloud.app/blog/why-is-brand-identity-important-understanding-the-benefits-of-establishing-a-unique-brand-identity), figma file to view colours https://www.figma.com/file/mBg74uj7xVPxMo4A0iOOVP/outreachy-project?type=design&node-id=0%3A1&mode=design&t=jbYkvUAAg5zRgutj-1

**Comment by sxryadipta** [comment]
Is this issue still active?
