### ISSUE TITLE
Saving and loading from state

### ISSUE THREAD

**Issue by lastlegion** [camicroscope/caMicroscope#8]
We have the ability to store and load view state(i.e. zoom and pan position). The viewer gives a sharable link that can be used to launch camicroscope from this old state. 

We need to document the types of state we want to support, example: 
`viewport`, `algorithms` etc. so that external agents can push this state information too.

**Comment by birm** [comment]
Concept: save in localstorage so that it persists, then allow generation of urls from this for sharing. This should be done at image level. We need a mechanism to make sure it's valid as well.

**Comment by birm** [comment]
New concept: A dictionary of variables to use encoded in base64 or similar with no need for localstorage (browser long term storage) or a database.

**Comment by birm** [comment]
view state added in #55, should expand as we go
