### ISSUE TITLE
duplicated config keys

### ISSUE THREAD

**Issue by tdiprima** [camicroscope/caMicroscope#81]
There are two array keys in `config.php` that have been duplicated, and defined differently.  Could you guys please coordinate & help sort this out?

**config.php in develop branch**
1) **"[deleteAnnotation](https://github.com/camicroscope/caMicroscope/blob/develop/api/Configuration/config.php#L44)"** was defined 2 years ago.
Then it was **[defined again](https://github.com/camicroscope/caMicroscope/blob/develop/api/Configuration/config.php#L69)** in the same file 6 months ago.

2) **[retrieveTemplate](https://github.com/camicroscope/caMicroscope/blob/develop/api/Configuration/config.php#L37)** was defined about a year ago...
And then it was **[defined again](https://github.com/camicroscope/caMicroscope/blob/develop/api/Configuration/config.php#L79)** in the same file about 6 months ago.

@lastlegion @bridge2014

**Comment by birm** [comment]
This code is not part of the refactor; closing.
