### ISSUE TITLE
Introducing Website-wide Dark Mode with Seamless Switching

### ISSUE THREAD

**Issue by barchakuz** [camicroscope/caMicroscope#819]
### Summary:
The proposed feature aims to introduce a dark mode system to the entire caMicroscope website, allowing users to toggle between light and dark modes seamlessly. This feature will enhance user experience and accessibility by providing an alternative color scheme that is easier on the eyes, especially in low-light environments.

### Background:
Dark mode has become a popular feature in web applications and websites due to its benefits in reducing eye strain, improving readability, and conserving battery life on devices with OLED screens. By implementing dark mode in caMicroscope, we can cater to users' preferences and offer a more comfortable viewing experience across different environments.

### Use Cases:
- Reduced Eye Strain: Users can switch to dark mode to reduce eye strain, particularly when viewing the website for extended periods.
- Improved Readability: Dark mode enhances readability by providing a high-contrast color scheme, making text and visuals stand out more prominently.
- Enhanced Accessibility: Dark mode caters to users with visual impairments or sensitivity to bright light, ensuring accessibility for a wider range of users.
- Battery Conservation: On devices with OLED screens, dark mode can help conserve battery life by emitting less light compared to light mode.

### Implementation:
- Dark Mode Toggle: Add a toggle switch in the website footer to allow users to switch between light and dark modes. This switch should be persistent across all pages and should store the user's preference in local storage.
- CSS Styling: Implement CSS styles for dark mode to adjust the color scheme of text, background, buttons, and other elements accordingly. Use CSS variables or separate CSS files for light and dark modes to streamline maintenance.
- JavaScript Logic: Write JavaScript code to handle the toggle switch functionality, including enabling/disabling dark mode and storing the user's preference in local storage. Ensure that this logic is applied consistently across all pages of the website.

### Expected Impact:
- Improved User Experience: The introduction of dark mode will enhance user experience by providing a customizable viewing option that suits individual preferences and environments.
- Increased Accessibility: Dark mode improves accessibility for users with visual impairments or sensitivity to bright light, ensuring inclusivity and usability for all users.
- Positive Feedback: Implementing dark mode is likely to receive positive feedback from users who appreciate the flexibility and customization options offered by the website.

### Additional Notes:
Conduct user testing and gather feedback during the implementation phase to ensure that the dark mode feature meets users' expectations and requirements.
Consider providing keyboard shortcuts or accessibility features to facilitate toggling between light and dark modes for users who rely on assistive technologies.
Regularly monitor and update the dark mode feature based on user feedback and evolving design trends to maintain an optimal user experience.

**Comment by Navya-Verma11** [comment]
I am interested on working on this issue, could you please assign it to me?

**Comment by barchakuz** [comment]
Hey @Navya-Verma11 Thank you for attentions, 
these are just issues i find while testing and working on these issues only possible when approved by mentor.

**Comment by AkshadGawde** [comment]
Hey,
I'm interested for fixing this issue. Could you please guide me on how to start the development server using npm or pnpm?
also it would be great if you can assign this issue to me. 

Thanks in advance for your help!

Best regards,
Akshad Gawde
