### ISSUE TITLE
[Accessibility] Info Page: Zooming disabled in mobile view

### ISSUE THREAD

**Issue by nwanduka** [camicroscope/caMicroscope#830]
**Describe the bug**
Zooming is disabled on mobile view of the Info Page.
User Impact: **Critical**
Tool used: Axe

**To Reproduce**
1. Go to http://localhost:4010/apps/Info.html
2. Right-click on the page and click "inspect" to open the developer tools window
3. Zoom in on the Info page while it's in desktop view. The page zooms in and out.
4. Then switch to mobile view in the inspect panel and try to zoom. You'd notice that zoom doesn't work in mobile view

**Expected behavior**
The info page contains a table that fills a desktop view. In mobile view, only a small part of the table is shown. So to view the rest of the table, users need to be able to scale the table up or down by zooming.

**Screenshots**
![image](https://github.com/camicroscope/caMicroscope/assets/122698422/7064f708-4e31-4f8d-8964-cb42fee37838)

![Zoom accessibility issue](https://github.com/camicroscope/caMicroscope/assets/122698422/e7f2105e-ef9f-473d-913c-22df509044ac)

**Desktop (please complete the following information):**
 - OS: [Windows
 - Browser: Microsoft Edge

**Why is this important?**
The user-scalable="no" parameter inside the content attribute of <meta name="viewport"> element disables zooming on a page. The maximum-scale parameter limits the amount the user can zoom. This is problematic for people with low vision who rely on screen magnifiers to properly see the contents of a web page.

**How to Fix the Problem**
Remove the user-scalable="no" parameter from the content attribute of the <meta name="viewport"> element in order to allow zooming and ensure the maximum-scale parameter is not less than 2.

**Comment by Ayesh-07** [comment]
@nwanduka 
Fixed disabled in mobile #830
I would appreciate a review of my work to ensure it meets the project's standards.
