### ISSUE TITLE
Bug : Responsive table duplication on mobile screens due to stacktable.js multiple initializations

### ISSUE THREAD

**Issue by harshpreet14** [camicroscope/caMicroscope#847]
**Describe the bug**
The responsive tables rendered on mobile screens exhibit duplicated tables. The issue is caused by multiple instances of responsive tables being initialized by the stacktable.js plugin, without the previous instances being cleared from the DOM. This results in stacked tables accumulating and rendering duplicate content.

**To Reproduce**
1. Navigate to the Slides table page on a desktop browser.
2. Activate responsive design mode, simulating a mobile viewport.
3. Observe the manifestation of duplicate table instances indicated by multiple .stacktable.small-only elements.

**Expected behavior**
There should be no table duplicates in the table.html page. 

**Screenshots**

<img width="960" alt="Screenshot 2024-03-22 202425" src="https://github.com/camicroscope/caMicroscope/assets/114172812/86044043-54d9-4599-9215-5dbaf25d74ee">

<img width="959" alt="image" src="https://github.com/camicroscope/caMicroscope/assets/114172812/35f619d3-4618-4dd0-b3f0-1a67d718e827">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 123.0.6312.58 (Official Build) (64-bit)

**Additional context**
When the page is loaded or when certain actions trigger a table refresh on mobile devices, the stacktable.js plugin is called to create the mobile-friendly table layout. If the plugin is called multiple times without proper cleanup, each call generates a new stacked table, leading to multiple stacked tables being inserted into the DOM.

**Comment by birm** [comment]
Fixed in #1040
