### ISSUE TITLE
Sign in Page on the sign up page doesn't work properly

### ISSUE THREAD

**Issue by CodebyCc** [camicroscope/caMicroscope#867]
The sign-in page that allows existing users to login doesn't work properly on the sign up page

**Comment by AkshadGawde** [comment]
Hey,
I'm currently working on this issue and I need some assistance. Could you please guide me on how to start the development server using npm or pnpm?

Thanks in advance for your help!

Best regards,
Akshad Gawde

**Comment by CodebyCc** [comment]
> Hey, I'm currently working on this issue and I need some assistance. Could you please guide me on how to start the development server using npm or pnpm?
> 
> Thanks in advance for your help!
> 
> Best regards, Akshad Gawde

Hi Akshad ,

kindly email me so we both work on it tomorrow. Ciici6440@gmail.com.

**Comment by AkshadGawde** [comment]
> > Hey, I'm currently working on this issue and I need some assistance. Could you please guide me on how to start the development server using npm or pnpm?
> > Thanks in advance for your help!
> > Best regards, Akshad Gawde
> 
> Hi Akshad ,
> 
> kindly email me so we both work on it tomorrow. [Ciici6440@gmail.com](mailto:Ciici6440@gmail.com).


I have emailed you regarding the same .

**Comment by birm** [comment]
Can you explain what you expected to see and what you actually see?

**Comment by AkshadGawde** [comment]
> Can you explain what you expected to see and what you actually see?

Thanks for your prompt response! To clarify, I expected to see the development server for caMicroscope start up successfully when using npm or pnpm commands. However, I'm encountering some issues or errors during the process. 

Looking forward to your assistance.

**Comment by birm** [comment]
Oh! We wouldn't usually run camicroscope with npm directly; the login page is injected as a configuration file when used with docker compose https://github.com/camicroscope/Distro/blob/218d97339fd8d237ca1574c881ff1439f2098220/develop.yml#L21

**Comment by ujjwaldubey1** [comment]
Hi @birm  can you provide some screenshots of the issue because when i am clicking on the "Already have account " there is an error page not found is that actual error or is it my server specific ??
