### ISSUE TITLE
UI Issue: Duplicated Buttons on 'Help/User Guide' Selection

### ISSUE THREAD

**Issue by barchakuz** [camicroscope/caMicroscope#894]
**Describe the bug**
On the Workbench page, clicking the "Options" button in the navigation bar opens a list of two options. When selecting the "Help/User Guide" option, a message is displayed along with two buttons, resulting in a UI that does not adhere to professional standards.

**To Reproduce**
1. Launch the project.
2. Navigate to the Workbench page.
3. Click on the "Options" button in the navigation bar.
4. Select the "Help/User Guide" button.
5. Observe the duplicated buttons.

**Expected behavior**
The expected behavior is that selecting the "Help/User Guide" option should display the message and buttons without duplication, ensuring a clear and professional user interface.

**Desktop :**
 - OS: Window 10
 - Browser chrome
 - Version 22

**Screenshot:**
![1](https://github.com/camicroscope/caMicroscope/assets/66128370/78382db0-28b6-4d19-b355-8bf9165dfc3a)

**Additional context**
This issue detracts from the professionalism and usability of the UI. Addressing this issue will enhance the user experience and ensure adherence to professional UI standards.

**Comment by akash205sharma** [comment]
@barchakuz please assign this to me
