### ISSUE TITLE
Non compliance to W3C standards

### ISSUE THREAD

**Issue by gbengaoluwadahunsi** [camicroscope/caMicroscope#912]
Describe the bug
The landing page is not compliant with W3C standards despite recent updates. Notable adjustments include the addition of a doctype declaration, the use of the HTML lang attribute, and the removal of the frameborder attribute from iframes.

To Reproduce

Navigate to the landing page.
Inspect the HTML structure and attributes.
Note the absence of compliance with W3C standards.
Expected behavior
The landing page should adhere to W3C standards, including proper use of doctype, HTML tag, lang attribute, and adherence to iframe border specifications.

**Comment by ujjwaldubey1** [comment]
@gbengaoluwadahunsi  I have opened one Pull request for this issue .
