### ISSUE TITLE
readme.md is quite out of date

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#94]

**Comment by tdiprima** [comment]
While we're at it... wondering if we should "headerize" the top portion.

The part that says:
"caMicroscope - A Web Based Annotation and Visualization Platform for Digitized Whole Slide Images"
 
Wondering if it should look like...
# caMicroscope
## A Web Based Annotation and Visualization Platform for Digitized Whole Slide Images

**Comment by birm** [comment]
I've done some cleanup/updates to readme. This included adding your names to the contributor section, @tdiprima and @bridge2014; feel free to update accordingly.
