### ISSUE TITLE
Mark Point Editing Should Only Be Active if actively activated

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#943]
The points editing conflicts with other viewer functions, and it is easy to accidentally mess with annotations.

**Comment by birm** [comment]
It also ghosts incorrectly if you change zoom
<img width="940" alt="Screenshot 2024-04-03 at 4 09 31 PM" src="https://github.com/camicroscope/caMicroscope/assets/4951803/5b1d11de-7ae7-4d13-828f-6900e1bd2dc8">

**Comment by lbhnsh** [comment]
Hi, can you assign this issue to me?
