### ISSUE TITLE
PHP Api Endpoint Reorganization and Documentation

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#95]
in api/Data/ there are a lot of .php files acting as api endpoints. It's not very well organized; we should determine a clear organization going forward and document which endpoints do what.

**Comment by tdiprima** [comment]
One of them is mine: `getOverlayTiles.php`.  And it's for getting the file system tile location for these files.

I guess we could look at these php files and see if any are doing the exact same thing.  Even better -- if they're doing the exact same thing, and not being used.  Then we can archive them or get rid of them or something.

We should rename the ones named `something-clone.php`.  Right?  

Like `getMultipleAnnotsClone.php`, `getPropertiesClone.php`, `retrieveTemplateClone.php`.  At the meeting @bridge2014 indicated that he knew something about one or more of them.

**Comment by birm** [comment]
Does it make sense to have one file for each "kind" of object to post/get and use url parameters to specify what kind of query it is as applicable? 

For example, should we merge all annotation getters into a method which could accept both spatial and nonspatial queries, and call the appropriate bindaas call in each case?

**Comment by tdiprima** [comment]
Yes.  First I propose a quick cleanup (I can do it... I really need you to continue with the magnifier).  The attached list is where each of the 35 files in api/Data is being referenced from.

There are a few things I marked with a `<-- ??` -- for things I don't think are in use any longer, basically things we'd need to dive deeper into.

[api_Data_files.txt](https://github.com/camicroscope/caMicroscope/files/1831060/api_Data_files.txt)

**Comment by birm** [comment]
Moved to QUIP-299
