### ISSUE TITLE
[UX] [Accessibility] Steps to Upload a Slide

### ISSUE THREAD

**Issue by nwanduka** [camicroscope/caMicroscope#965]
**Describe the bug**
In the upload a slide modal, the instruction to successfully upload a slide is presented as bullet points. Users with screen readers would have trouble understanding the sequence of steps.

**To Reproduce**
1. Go to '[Slides](http://localhost:4010/apps/table.html)'
2. Click on 'Upload'

**Expected behavior**
A better UX would be to use numbered lists or "Step 1:, Step 2:" and so on.

**Screenshots**
<img width="581" alt="Capture" src="https://github.com/camicroscope/caMicroscope/assets/122698422/d7138537-c993-4bab-bf41-ee086e8dc86b">

**Comment by birm** [comment]
I'm seeing different text; am I looking on the wrong branch? https://github.com/camicroscope/caMicroscope/blob/a9058bd34392c9398625b669d795f7d0500e7ff9/apps/table.html#L212

**Comment by nwanduka** [comment]
Ah! You're not on the wrong branch. I just realized I didn't run the build command to pull recent changes. I'll update the issue description.
