### ISSUE TITLE
[Accessibility] Slides Page: Buttons have low color contrast

### ISSUE THREAD

**Issue by nwanduka** [camicroscope/caMicroscope#971]
**Description**
The Info, DICOM, and Report it (at the footer) buttons don't meet the minimum contrast ratio requirement.

**Screenshots**
![image](https://github.com/camicroscope/caMicroscope/assets/122698422/d6c55cd1-a1f1-4f03-ae0d-ad901e849b05)

Result for DICOM button
![image](https://github.com/camicroscope/caMicroscope/assets/122698422/741ba74c-0575-4e43-b78d-f4ff186ed558)

Result for Info button
![image](https://github.com/camicroscope/caMicroscope/assets/122698422/d4bae32c-167d-4dfe-8b1d-c2b552da55c1)

Result for "Report it" hyperlink
![image](https://github.com/camicroscope/caMicroscope/assets/122698422/58f9a20f-1af0-47d6-9a09-3e4ec623de2e)

**Proposed Fix**
Increase contrast between the background and foreground colors of the affected buttons

**Comment by Dipti0704** [comment]
i am Interested please assign me this issue
