### ISSUE TITLE
[Accessibility] Slide Viewer: Tool icons on top left don't have contextual labels/names.

### ISSUE THREAD

**Issue by nwanduka** [camicroscope/caMicroscope#981]
**Describe the bug**
Screen reader calls out a different name from what the tool tip shows when you place a mouse on the icons in the toolbar. For instance, the "draw" icon is read as "create", the "magnifier" icon as "search". 

**Expected behavior**
Icons should have contextual and corresponding labels/names.

**Screenshots**
![image](https://github.com/camicroscope/caMicroscope/assets/122698422/fe924f88-5191-4af3-a220-578ebf3ccfea)

**Comment by Joice-crypto** [comment]
Hello, I would like to work on this, please tell me which part of the code this is in.

**Comment by ujjwaldubey1** [comment]
@nwanduka  I have fixed the issue but not able to test I am also confused that i have the website 
![image](https://github.com/user-attachments/assets/db003d65-4571-4cee-8c77-b72e6dfe8c23)
and when i am searching for the camicroscope the website is showing is this
![image](https://github.com/user-attachments/assets/d188d26c-f087-42bd-9453-c476898e4afb)
what are these can you help me to figure it out ??

**Comment by birm** [comment]
@ujjwaldubey1 the first image from your screeenshot is from the caMicroscope app (landing), whereas the second is from our public webpage (https://github.com/camicroscope/camicroscope.github.io)

**Comment by ujjwaldubey1** [comment]
@birm I have cloned this repo and after running first one is showing, i was not able to find the section where the error is located in website can you explain the whole structure and how can i get to the error step by step .
Thank You!!

**Comment by nwanduka** [comment]
@ujjwaldubey1, the issue is on the toolbar in the Slide Viewer page. To view it,
- go to the "slide" page on the web app (the first image you shared)
- upload a slide if you haven't already done so
- click on the slide you've uploaded to view it in the Slide Viewer.

Hope this helps.

**Comment by ujjwaldubey1** [comment]
@nwanduka 
![image](https://github.com/user-attachments/assets/2c0df64e-e083-4a2e-8624-dcdc4a940d25)
There is no option for upload or any other and adding collections it not responding any thing
