### ISSUE TITLE
Error during Docker build operation

### ISSUE THREAD

**Issue by nwanduka** [camicroscope/caMicroscope#986]
**Describe the bug**
I'm facing challenges while attempting to set up and run caMicroscope on my local machine using Docker. Initially, the site was running but not showing me the most recent version of caMicroscope. I pulled changes from the origin to my cloned branch then when I ran the build command, I encountered issues related to cloning the `orthanc-indexer` repository (see first screenshot).

Next, I tried deleting previous forks and creating new ones to build the site afresh. I now face consistent `git clone` failures during Docker build with the following error: `failed to solve: process "/bin/sh -c git clone https://github.com/${fork:-camicroscope}/camicroscope.git --branch=${viewer:-master} --depth 1"` (see second screenshot)

I would appreciate any guidance or suggestions on how to successfully resolve these `git clone` errors during Docker build, or any insights into what might be causing these issues.

**Expected behavior**

**Screenshots**
![image](https://github.com/camicroscope/caMicroscope/assets/122698422/fa3f9d14-8e50-4327-85f4-a0a2b451470e)

![image](https://github.com/camicroscope/caMicroscope/assets/122698422/5ed32b15-3e9a-4640-a420-7bf23df0a631)

**Comment by birm** [comment]
I've added a v3.12.0 for orthanc indexer; I must've incorrectly bumped the version in a release. https://github.com/camicroscope/orthanc-indexer/releases/tag/v3.12.0

Does trying again resolve the issue?

**Comment by nwanduka** [comment]
Yes, it works well now. It's showing the updated version of the site. Thanks a lot. I'll close this issue now.
